// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authproxy/authproxy_grpc_pb/authproxy_grpc_pb.proto

package authproxy_grpc_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TraceContext struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=TraceId,proto3" json:"TraceId,omitempty"`
	App                  string   `protobuf:"bytes,2,opt,name=App,proto3" json:"App,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=Host,proto3" json:"Host,omitempty"`
	ActionName           string   `protobuf:"bytes,4,opt,name=ActionName,proto3" json:"ActionName,omitempty"`
	UserName             string   `protobuf:"bytes,5,opt,name=UserName,proto3" json:"UserName,omitempty"`
	RoleName             string   `protobuf:"bytes,6,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	ProjectName          string   `protobuf:"bytes,7,opt,name=ProjectName,proto3" json:"ProjectName,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,8,opt,name=ProjectRoleName,proto3" json:"ProjectRoleName,omitempty"`
	StatusCode           int64    `protobuf:"varint,9,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Err                  string   `protobuf:"bytes,10,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceContext) Reset()         { *m = TraceContext{} }
func (m *TraceContext) String() string { return proto.CompactTextString(m) }
func (*TraceContext) ProtoMessage()    {}
func (*TraceContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c15446ed5ade30f, []int{0}
}

func (m *TraceContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceContext.Unmarshal(m, b)
}
func (m *TraceContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceContext.Marshal(b, m, deterministic)
}
func (m *TraceContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceContext.Merge(m, src)
}
func (m *TraceContext) XXX_Size() int {
	return xxx_messageInfo_TraceContext.Size(m)
}
func (m *TraceContext) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceContext.DiscardUnknown(m)
}

var xxx_messageInfo_TraceContext proto.InternalMessageInfo

func (m *TraceContext) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *TraceContext) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *TraceContext) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *TraceContext) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *TraceContext) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TraceContext) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *TraceContext) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *TraceContext) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

func (m *TraceContext) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *TraceContext) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ActionRequest struct {
	Tctx                 *TraceContext `protobuf:"bytes,1,opt,name=Tctx,proto3" json:"Tctx,omitempty"`
	Queries              []*Query      `protobuf:"bytes,2,rep,name=Queries,proto3" json:"Queries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ActionRequest) Reset()         { *m = ActionRequest{} }
func (m *ActionRequest) String() string { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()    {}
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c15446ed5ade30f, []int{1}
}

func (m *ActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRequest.Unmarshal(m, b)
}
func (m *ActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRequest.Marshal(b, m, deterministic)
}
func (m *ActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRequest.Merge(m, src)
}
func (m *ActionRequest) XXX_Size() int {
	return xxx_messageInfo_ActionRequest.Size(m)
}
func (m *ActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRequest proto.InternalMessageInfo

func (m *ActionRequest) GetTctx() *TraceContext {
	if m != nil {
		return m.Tctx
	}
	return nil
}

func (m *ActionRequest) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

type Query struct {
	Kind                 string            `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	StrParams            map[string]string `protobuf:"bytes,2,rep,name=StrParams,proto3" json:"StrParams,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NumParams            map[string]int64  `protobuf:"bytes,3,rep,name=NumParams,proto3" json:"NumParams,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c15446ed5ade30f, []int{2}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Query) GetStrParams() map[string]string {
	if m != nil {
		return m.StrParams
	}
	return nil
}

func (m *Query) GetNumParams() map[string]int64 {
	if m != nil {
		return m.NumParams
	}
	return nil
}

type ActionReply struct {
	Tctx                 *TraceContext `protobuf:"bytes,1,opt,name=Tctx,proto3" json:"Tctx,omitempty"`
	Response             string        `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ActionReply) Reset()         { *m = ActionReply{} }
func (m *ActionReply) String() string { return proto.CompactTextString(m) }
func (*ActionReply) ProtoMessage()    {}
func (*ActionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c15446ed5ade30f, []int{3}
}

func (m *ActionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionReply.Unmarshal(m, b)
}
func (m *ActionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionReply.Marshal(b, m, deterministic)
}
func (m *ActionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionReply.Merge(m, src)
}
func (m *ActionReply) XXX_Size() int {
	return xxx_messageInfo_ActionReply.Size(m)
}
func (m *ActionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ActionReply proto.InternalMessageInfo

func (m *ActionReply) GetTctx() *TraceContext {
	if m != nil {
		return m.Tctx
	}
	return nil
}

func (m *ActionReply) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*TraceContext)(nil), "authproxy_grpc_pb.TraceContext")
	proto.RegisterType((*ActionRequest)(nil), "authproxy_grpc_pb.ActionRequest")
	proto.RegisterType((*Query)(nil), "authproxy_grpc_pb.Query")
	proto.RegisterMapType((map[string]int64)(nil), "authproxy_grpc_pb.Query.NumParamsEntry")
	proto.RegisterMapType((map[string]string)(nil), "authproxy_grpc_pb.Query.StrParamsEntry")
	proto.RegisterType((*ActionReply)(nil), "authproxy_grpc_pb.ActionReply")
}

func init() {
	proto.RegisterFile("authproxy/authproxy_grpc_pb/authproxy_grpc_pb.proto", fileDescriptor_4c15446ed5ade30f)
}

var fileDescriptor_4c15446ed5ade30f = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xed, 0xa6, 0x49, 0x26, 0x40, 0x61, 0xc5, 0x61, 0x15, 0x24, 0x88, 0x72, 0x21, 0x27,
	0x5b, 0x4a, 0x2e, 0x08, 0xb8, 0xb4, 0x55, 0x04, 0x08, 0xa9, 0x0a, 0x6e, 0xb9, 0x70, 0xa0, 0xda,
	0x38, 0x23, 0xd7, 0x24, 0xf6, 0x2e, 0xfb, 0x83, 0xec, 0xf7, 0x81, 0xf7, 0x44, 0xbb, 0xb1, 0x8d,
	0x4b, 0x80, 0x4a, 0xdc, 0xbe, 0x9f, 0x99, 0xcf, 0xbb, 0xb3, 0x1e, 0x58, 0x30, 0xa3, 0x6f, 0x84,
	0xe4, 0x65, 0x15, 0xb5, 0xe8, 0x3a, 0x95, 0x22, 0xb9, 0x16, 0xeb, 0x43, 0x25, 0x14, 0x92, 0x6b,
	0x4e, 0x1e, 0x1d, 0x18, 0xd3, 0xef, 0x3e, 0xdc, 0xbb, 0x92, 0x2c, 0xc1, 0x73, 0x5e, 0x68, 0x2c,
	0x35, 0xa1, 0xd0, 0x77, 0xfc, 0xdd, 0x86, 0x7a, 0x13, 0x6f, 0x36, 0x8c, 0x1b, 0x4a, 0x1e, 0x42,
	0x70, 0x2a, 0x04, 0xf5, 0x9d, 0x6a, 0x21, 0x21, 0x70, 0xf4, 0x96, 0x2b, 0x4d, 0x03, 0x27, 0x39,
	0x4c, 0x9e, 0x02, 0x9c, 0x26, 0x3a, 0xe3, 0xc5, 0x05, 0xcb, 0x91, 0x1e, 0x39, 0xa7, 0xa3, 0x90,
	0x31, 0x0c, 0x3e, 0x2a, 0x94, 0xce, 0xed, 0x39, 0xb7, 0xe5, 0xd6, 0x8b, 0xf9, 0x0e, 0x9d, 0x77,
	0xbc, 0xf7, 0x1a, 0x4e, 0x26, 0x30, 0x5a, 0x49, 0xfe, 0x05, 0x13, 0xed, 0xec, 0xbe, 0xb3, 0xbb,
	0x12, 0x99, 0xc1, 0x49, 0x4d, 0xdb, 0x90, 0x81, 0xab, 0xfa, 0x5d, 0xb6, 0x67, 0xbc, 0xd4, 0x4c,
	0x1b, 0x75, 0xce, 0x37, 0x48, 0x87, 0x13, 0x6f, 0x16, 0xc4, 0x1d, 0xc5, 0xde, 0x74, 0x29, 0x25,
	0x85, 0xfd, 0x4d, 0x97, 0x52, 0x4e, 0x4b, 0xb8, 0xbf, 0xbf, 0x43, 0x8c, 0x5f, 0x0d, 0x2a, 0x4d,
	0x16, 0x70, 0x74, 0x95, 0xe8, 0xd2, 0xcd, 0x68, 0x34, 0x7f, 0x16, 0x1e, 0x8e, 0xbc, 0x3b, 0xd5,
	0xd8, 0x15, 0x93, 0x39, 0xf4, 0x3f, 0x18, 0x94, 0x19, 0x2a, 0xea, 0x4f, 0x82, 0xd9, 0x68, 0x4e,
	0xff, 0xd0, 0x67, 0x2b, 0xaa, 0xb8, 0x29, 0x9c, 0xfe, 0xf0, 0xa1, 0xe7, 0x24, 0x3b, 0xed, 0xf7,
	0x59, 0xd1, 0x3c, 0x8b, 0xc3, 0x64, 0x09, 0xc3, 0x4b, 0x2d, 0x57, 0x4c, 0xb2, 0xbc, 0xc9, 0x7c,
	0xfe, 0xb7, 0xcc, 0xb0, 0xad, 0x5c, 0x16, 0x5a, 0x56, 0xf1, 0xaf, 0x4e, 0x1b, 0x73, 0x61, 0xf2,
	0x3a, 0x26, 0xb8, 0x23, 0xa6, 0xad, 0xac, 0x63, 0x5a, 0x3e, 0x7e, 0x0d, 0x0f, 0x6e, 0x7f, 0xc3,
	0x4e, 0x72, 0x8b, 0x55, 0x7d, 0x64, 0x0b, 0xc9, 0x63, 0xe8, 0x7d, 0x63, 0x3b, 0x83, 0xf5, 0x7f,
	0xb4, 0x27, 0x2f, 0xfd, 0x17, 0x9e, 0xed, 0xbe, 0x1d, 0x7d, 0x57, 0x77, 0xd0, 0xe9, 0x9e, 0x7e,
	0x86, 0x51, 0xf3, 0x42, 0x62, 0x57, 0xfd, 0xdf, 0xfb, 0x8c, 0x61, 0x20, 0x51, 0x09, 0x5e, 0xa8,
	0xe6, 0x78, 0x2d, 0x3f, 0xcb, 0xe1, 0x49, 0xc6, 0x43, 0xdb, 0x1c, 0x62, 0xc9, 0x72, 0xb1, 0x43,
	0x15, 0x4a, 0x6e, 0x34, 0xa6, 0x26, 0xdb, 0xe0, 0xd9, 0x49, 0x6c, 0xf1, 0x1b, 0x8b, 0x57, 0x76,
	0xd7, 0x56, 0xde, 0xa7, 0x57, 0x69, 0xa6, 0x6f, 0xcc, 0x3a, 0x4c, 0x78, 0x1e, 0xa9, 0xca, 0x14,
	0xdb, 0x4c, 0xb3, 0x0d, 0x8b, 0x52, 0xce, 0x84, 0x88, 0xc4, 0x36, 0x8d, 0xfe, 0xb1, 0xc2, 0xeb,
	0x63, 0xb7, 0xb1, 0x8b, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xb6, 0x38, 0x9e, 0xe8, 0x03,
	0x00, 0x00,
}
