// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor_api_grpc_pb.proto

package monitor_api_grpc_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{0}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{1}
}
func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (dst *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(dst, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//
// Node
//
type GetNodeRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,5,opt,name=project_role_name,json=projectRoleName" json:"project_role_name,omitempty"`
	Target               string   `protobuf:"bytes,6,opt,name=target" json:"target,omitempty"`
	Cluster              string   `protobuf:"bytes,7,opt,name=cluster" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRequest) Reset()         { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()    {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{2}
}
func (m *GetNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRequest.Unmarshal(m, b)
}
func (m *GetNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRequest.Marshal(b, m, deterministic)
}
func (dst *GetNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRequest.Merge(dst, src)
}
func (m *GetNodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRequest.Size(m)
}
func (m *GetNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRequest proto.InternalMessageInfo

func (m *GetNodeRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetNodeRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetNodeRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *GetNodeRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetNodeRequest) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

func (m *GetNodeRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *GetNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type GetNodeReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeReply) Reset()         { *m = GetNodeReply{} }
func (m *GetNodeReply) String() string { return proto.CompactTextString(m) }
func (*GetNodeReply) ProtoMessage()    {}
func (*GetNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{3}
}
func (m *GetNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeReply.Unmarshal(m, b)
}
func (m *GetNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeReply.Marshal(b, m, deterministic)
}
func (dst *GetNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeReply.Merge(dst, src)
}
func (m *GetNodeReply) XXX_Size() int {
	return xxx_messageInfo_GetNodeReply.Size(m)
}
func (m *GetNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeReply proto.InternalMessageInfo

func (m *GetNodeReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetNodeReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetNodeReply) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type UpdateNodeRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role" json:"role,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	StatusReason         string   `protobuf:"bytes,6,opt,name=status_reason,json=statusReason" json:"status_reason,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=state" json:"state,omitempty"`
	StateReason          string   `protobuf:"bytes,8,opt,name=state_reason,json=stateReason" json:"state_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeRequest) Reset()         { *m = UpdateNodeRequest{} }
func (m *UpdateNodeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeRequest) ProtoMessage()    {}
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{4}
}
func (m *UpdateNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeRequest.Unmarshal(m, b)
}
func (m *UpdateNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeRequest.Merge(dst, src)
}
func (m *UpdateNodeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeRequest.Size(m)
}
func (m *UpdateNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeRequest proto.InternalMessageInfo

func (m *UpdateNodeRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *UpdateNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateNodeRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *UpdateNodeRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UpdateNodeRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateNodeRequest) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *UpdateNodeRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *UpdateNodeRequest) GetStateReason() string {
	if m != nil {
		return m.StateReason
	}
	return ""
}

type UpdateNodeReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeReply) Reset()         { *m = UpdateNodeReply{} }
func (m *UpdateNodeReply) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeReply) ProtoMessage()    {}
func (*UpdateNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{5}
}
func (m *UpdateNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeReply.Unmarshal(m, b)
}
func (m *UpdateNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeReply.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeReply.Merge(dst, src)
}
func (m *UpdateNodeReply) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeReply.Size(m)
}
func (m *UpdateNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeReply proto.InternalMessageInfo

func (m *UpdateNodeReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *UpdateNodeReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Node struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Cluster              string               `protobuf:"bytes,3,opt,name=cluster" json:"cluster,omitempty"`
	Name                 string               `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Kind                 string               `protobuf:"bytes,5,opt,name=kind" json:"kind,omitempty"`
	Role                 string               `protobuf:"bytes,6,opt,name=role" json:"role,omitempty"`
	Status               string               `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
	StatusReason         string               `protobuf:"bytes,8,opt,name=status_reason,json=statusReason" json:"status_reason,omitempty"`
	State                string               `protobuf:"bytes,9,opt,name=state" json:"state,omitempty"`
	StateReason          string               `protobuf:"bytes,10,opt,name=state_reason,json=stateReason" json:"state_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{6}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Node) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Node) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Node) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Node) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Node) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *Node) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Node) GetStateReason() string {
	if m != nil {
		return m.StateReason
	}
	return ""
}

//
// Report
//
type ReportRequest struct {
	Index                string   `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,3,rep,name=logs" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{7}
}
func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (dst *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(dst, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ReportRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ReportRequest) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type ReportReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportReply) Reset()         { *m = ReportReply{} }
func (m *ReportReply) String() string { return proto.CompactTextString(m) }
func (*ReportReply) ProtoMessage()    {}
func (*ReportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{8}
}
func (m *ReportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportReply.Unmarshal(m, b)
}
func (m *ReportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportReply.Marshal(b, m, deterministic)
}
func (dst *ReportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportReply.Merge(dst, src)
}
func (m *ReportReply) XXX_Size() int {
	return xxx_messageInfo_ReportReply.Size(m)
}
func (m *ReportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReportReply proto.InternalMessageInfo

func (m *ReportReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ReportReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Log struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Time                 string            `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	Log                  map[string]string `protobuf:"bytes,3,rep,name=log" json:"log,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{9}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (dst *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(dst, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Log) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Log) GetLog() map[string]string {
	if m != nil {
		return m.Log
	}
	return nil
}

//
// GetHost
//
type GetHostRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,5,opt,name=project_role_name,json=projectRoleName" json:"project_role_name,omitempty"`
	Index                string   `protobuf:"bytes,6,opt,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostRequest) Reset()         { *m = GetHostRequest{} }
func (m *GetHostRequest) String() string { return proto.CompactTextString(m) }
func (*GetHostRequest) ProtoMessage()    {}
func (*GetHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{10}
}
func (m *GetHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostRequest.Unmarshal(m, b)
}
func (m *GetHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostRequest.Marshal(b, m, deterministic)
}
func (dst *GetHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostRequest.Merge(dst, src)
}
func (m *GetHostRequest) XXX_Size() int {
	return xxx_messageInfo_GetHostRequest.Size(m)
}
func (m *GetHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostRequest proto.InternalMessageInfo

func (m *GetHostRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetHostRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetHostRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *GetHostRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetHostRequest) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

func (m *GetHostRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type GetHostReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Hosts                []*Host  `protobuf:"bytes,3,rep,name=hosts" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostReply) Reset()         { *m = GetHostReply{} }
func (m *GetHostReply) String() string { return proto.CompactTextString(m) }
func (*GetHostReply) ProtoMessage()    {}
func (*GetHostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{11}
}
func (m *GetHostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostReply.Unmarshal(m, b)
}
func (m *GetHostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostReply.Marshal(b, m, deterministic)
}
func (dst *GetHostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostReply.Merge(dst, src)
}
func (m *GetHostReply) XXX_Size() int {
	return xxx_messageInfo_GetHostReply.Size(m)
}
func (m *GetHostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostReply proto.InternalMessageInfo

func (m *GetHostReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetHostReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetHostReply) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type Host struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{12}
}
func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (dst *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(dst, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//
// GetLog
//
type GetLogRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,5,opt,name=project_role_name,json=projectRoleName" json:"project_role_name,omitempty"`
	Index                string   `protobuf:"bytes,6,opt,name=index" json:"index,omitempty"`
	LogName              string   `protobuf:"bytes,7,opt,name=log_name,json=logName" json:"log_name,omitempty"`
	LogHost              string   `protobuf:"bytes,8,opt,name=log_host,json=logHost" json:"log_host,omitempty"`
	LogTraceId           string   `protobuf:"bytes,9,opt,name=log_trace_id,json=logTraceId" json:"log_trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogRequest) Reset()         { *m = GetLogRequest{} }
func (m *GetLogRequest) String() string { return proto.CompactTextString(m) }
func (*GetLogRequest) ProtoMessage()    {}
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{13}
}
func (m *GetLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogRequest.Unmarshal(m, b)
}
func (m *GetLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogRequest.Marshal(b, m, deterministic)
}
func (dst *GetLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogRequest.Merge(dst, src)
}
func (m *GetLogRequest) XXX_Size() int {
	return xxx_messageInfo_GetLogRequest.Size(m)
}
func (m *GetLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogRequest proto.InternalMessageInfo

func (m *GetLogRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetLogRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetLogRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *GetLogRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetLogRequest) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

func (m *GetLogRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *GetLogRequest) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *GetLogRequest) GetLogHost() string {
	if m != nil {
		return m.LogHost
	}
	return ""
}

func (m *GetLogRequest) GetLogTraceId() string {
	if m != nil {
		return m.LogTraceId
	}
	return ""
}

type GetLogReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,3,rep,name=logs" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogReply) Reset()         { *m = GetLogReply{} }
func (m *GetLogReply) String() string { return proto.CompactTextString(m) }
func (*GetLogReply) ProtoMessage()    {}
func (*GetLogReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2, []int{14}
}
func (m *GetLogReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogReply.Unmarshal(m, b)
}
func (m *GetLogReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogReply.Marshal(b, m, deterministic)
}
func (dst *GetLogReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogReply.Merge(dst, src)
}
func (m *GetLogReply) XXX_Size() int {
	return xxx_messageInfo_GetLogReply.Size(m)
}
func (m *GetLogReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogReply proto.InternalMessageInfo

func (m *GetLogReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetLogReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetLogReply) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "monitor_api_grpc_pb.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "monitor_api_grpc_pb.StatusReply")
	proto.RegisterType((*GetNodeRequest)(nil), "monitor_api_grpc_pb.GetNodeRequest")
	proto.RegisterType((*GetNodeReply)(nil), "monitor_api_grpc_pb.GetNodeReply")
	proto.RegisterType((*UpdateNodeRequest)(nil), "monitor_api_grpc_pb.UpdateNodeRequest")
	proto.RegisterType((*UpdateNodeReply)(nil), "monitor_api_grpc_pb.UpdateNodeReply")
	proto.RegisterType((*Node)(nil), "monitor_api_grpc_pb.Node")
	proto.RegisterType((*ReportRequest)(nil), "monitor_api_grpc_pb.ReportRequest")
	proto.RegisterType((*ReportReply)(nil), "monitor_api_grpc_pb.ReportReply")
	proto.RegisterType((*Log)(nil), "monitor_api_grpc_pb.Log")
	proto.RegisterMapType((map[string]string)(nil), "monitor_api_grpc_pb.Log.LogEntry")
	proto.RegisterType((*GetHostRequest)(nil), "monitor_api_grpc_pb.GetHostRequest")
	proto.RegisterType((*GetHostReply)(nil), "monitor_api_grpc_pb.GetHostReply")
	proto.RegisterType((*Host)(nil), "monitor_api_grpc_pb.Host")
	proto.RegisterType((*GetLogRequest)(nil), "monitor_api_grpc_pb.GetLogRequest")
	proto.RegisterType((*GetLogReply)(nil), "monitor_api_grpc_pb.GetLogReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorApiClient is the client API for MonitorApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorApiClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeReply, error)
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportReply, error)
	GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostReply, error)
	GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogReply, error)
}

type monitorApiClient struct {
	cc *grpc.ClientConn
}

func NewMonitorApiClient(cc *grpc.ClientConn) MonitorApiClient {
	return &monitorApiClient{cc}
}

func (c *monitorApiClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error) {
	out := new(GetNodeReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeReply, error) {
	out := new(UpdateNodeReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/UpdateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportReply, error) {
	out := new(ReportReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostReply, error) {
	out := new(GetHostReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/GetHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogReply, error) {
	out := new(GetLogReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/GetLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorApiServer is the server API for MonitorApi service.
type MonitorApiServer interface {
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeReply, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeReply, error)
	Report(context.Context, *ReportRequest) (*ReportReply, error)
	GetHost(context.Context, *GetHostRequest) (*GetHostReply, error)
	GetLog(context.Context, *GetLogRequest) (*GetLogReply, error)
}

func RegisterMonitorApiServer(s *grpc.Server, srv MonitorApiServer) {
	s.RegisterService(&_MonitorApi_serviceDesc, srv)
}

func _MonitorApi_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/UpdateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/GetHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).GetHost(ctx, req.(*GetHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_GetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).GetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/GetLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).GetLog(ctx, req.(*GetLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor_api_grpc_pb.MonitorApi",
	HandlerType: (*MonitorApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _MonitorApi_Status_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _MonitorApi_GetNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _MonitorApi_UpdateNode_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _MonitorApi_Report_Handler,
		},
		{
			MethodName: "GetHost",
			Handler:    _MonitorApi_GetHost_Handler,
		},
		{
			MethodName: "GetLog",
			Handler:    _MonitorApi_GetLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor_api_grpc_pb.proto",
}

func init() {
	proto.RegisterFile("monitor_api_grpc_pb.proto", fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2)
}

var fileDescriptor_monitor_api_grpc_pb_db15766f525ac5a2 = []byte{
	// 847 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x45, 0xfd, 0x8e, 0xa4, 0xaa, 0xde, 0x1a, 0x85, 0x2c, 0x1f, 0x2c, 0xd3, 0x45, 0x61,
	0x14, 0x05, 0x5d, 0xd8, 0x40, 0xd1, 0xf6, 0x54, 0xbb, 0x2d, 0xdc, 0x00, 0x8e, 0x21, 0xd0, 0xce,
	0x2d, 0x80, 0x40, 0x8b, 0x1b, 0x86, 0x31, 0xc9, 0x65, 0x96, 0xcb, 0xc0, 0x7a, 0x85, 0x3c, 0x42,
	0x6e, 0x79, 0x9b, 0x20, 0x4f, 0x91, 0x53, 0x9e, 0x23, 0x98, 0xfd, 0x91, 0x25, 0x98, 0x92, 0x13,
	0xdd, 0x7c, 0x10, 0x30, 0xbf, 0xcb, 0x99, 0xef, 0x9b, 0x9d, 0x15, 0x6c, 0x27, 0x2c, 0x8d, 0x04,
	0xe3, 0x63, 0x3f, 0x8b, 0xc6, 0x21, 0xcf, 0x26, 0xe3, 0xec, 0xda, 0xcd, 0x38, 0x13, 0x8c, 0xfc,
	0x50, 0xe2, 0x1a, 0xec, 0x86, 0x8c, 0x85, 0x31, 0x3d, 0x94, 0x21, 0xd7, 0xc5, 0x8b, 0x43, 0x11,
	0x25, 0x34, 0x17, 0x7e, 0x92, 0xa9, 0x2c, 0xa7, 0x07, 0xdd, 0x4b, 0xe1, 0x8b, 0x22, 0xf7, 0xe8,
	0xeb, 0x82, 0xe6, 0xc2, 0xd9, 0x85, 0xb6, 0x31, 0x64, 0xf1, 0x94, 0x7c, 0x0f, 0x76, 0x92, 0x87,
	0x7d, 0x6b, 0x68, 0x1d, 0xb4, 0x3c, 0x14, 0x9d, 0xcf, 0x16, 0x7c, 0x77, 0x46, 0xc5, 0x05, 0x0b,
	0xa8, 0xce, 0x21, 0xdb, 0xd0, 0x14, 0xdc, 0x9f, 0xd0, 0x71, 0x14, 0xe8, 0xc8, 0x86, 0xd4, 0x9f,
	0x04, 0x64, 0x07, 0x5a, 0x45, 0x4e, 0xf9, 0x38, 0xf5, 0x13, 0xda, 0xaf, 0x48, 0x5f, 0x13, 0x0d,
	0x17, 0x7e, 0x42, 0xd1, 0xc9, 0x59, 0x4c, 0x95, 0xd3, 0x56, 0x4e, 0x34, 0x48, 0xe7, 0x1e, 0x74,
	0x32, 0xce, 0x5e, 0xd1, 0x89, 0x50, 0xfe, 0xaa, 0xf4, 0xb7, 0xb5, 0x4d, 0x86, 0xfc, 0x02, 0x9b,
	0x26, 0xe4, 0xee, 0x9c, 0x9a, 0x8c, 0xeb, 0x69, 0x87, 0x67, 0x8e, 0xfb, 0x11, 0xea, 0xc2, 0xe7,
	0x21, 0x15, 0xfd, 0xba, 0x0c, 0xd0, 0x1a, 0xe9, 0x43, 0x63, 0x12, 0x17, 0xb9, 0xa0, 0xbc, 0xdf,
	0x50, 0xa5, 0x6b, 0xd5, 0xe1, 0xd0, 0x99, 0xf5, 0x89, 0x50, 0xec, 0x42, 0x3b, 0x97, 0xc8, 0x8c,
	0x27, 0x2c, 0xa0, 0xb2, 0x51, 0xdb, 0x03, 0x65, 0xfa, 0x87, 0x05, 0x14, 0xb1, 0xa2, 0x9c, 0xeb,
	0x2e, 0x51, 0x24, 0x87, 0x50, 0x4b, 0x59, 0x40, 0xf3, 0xbe, 0x3d, 0xb4, 0x0f, 0xda, 0x47, 0xdb,
	0x6e, 0x19, 0x7d, 0xf2, 0x0b, 0x2a, 0xce, 0xf9, 0x64, 0xc1, 0xe6, 0xb3, 0x2c, 0xf0, 0x05, 0xfd,
	0x4a, 0x7c, 0x09, 0x54, 0xe7, 0xa0, 0x95, 0x32, 0xda, 0x6e, 0xa2, 0x34, 0xd0, 0x88, 0x4a, 0x19,
	0x6d, 0x08, 0x91, 0x46, 0x51, 0xca, 0x08, 0x89, 0xaa, 0x5e, 0x63, 0xa6, 0x35, 0xb2, 0x0f, 0x5d,
	0xdd, 0x28, 0xa7, 0x7e, 0xce, 0x52, 0x8d, 0x58, 0x27, 0xd7, 0x73, 0x81, 0x36, 0xb2, 0x05, 0x35,
	0xd4, 0xa9, 0x46, 0x4d, 0x29, 0x48, 0x9a, 0x14, 0x4c, 0x66, 0x53, 0x91, 0x26, 0x6d, 0x2a, 0xd1,
	0xf9, 0x17, 0x7a, 0xf3, 0x1d, 0xae, 0x87, 0xac, 0xf3, 0xa1, 0x02, 0x55, 0x3c, 0x80, 0xfc, 0x09,
	0x50, 0xc8, 0xe3, 0x82, 0xb1, 0x2f, 0x64, 0x6a, 0xfb, 0x68, 0xe0, 0xaa, 0xb1, 0x77, 0xcd, 0xd8,
	0xbb, 0x57, 0x66, 0xec, 0xbd, 0x96, 0x8e, 0x3e, 0x11, 0x98, 0x3a, 0xe1, 0xd4, 0xa4, 0x56, 0x1e,
	0x4e, 0xd5, 0xd1, 0x27, 0x0b, 0x53, 0x63, 0x2f, 0x4c, 0xcd, 0x8c, 0x90, 0x6a, 0x09, 0x21, 0xb5,
	0x12, 0x42, 0xea, 0xa5, 0x84, 0x34, 0x56, 0x13, 0xd2, 0x5c, 0x45, 0x48, 0x6b, 0x15, 0x21, 0x70,
	0x9f, 0x90, 0x04, 0xba, 0x1e, 0xcd, 0x18, 0x17, 0x66, 0xdc, 0xb6, 0xa0, 0x16, 0xa5, 0x01, 0xbd,
	0xd5, 0xb3, 0xa6, 0x14, 0x6c, 0x59, 0xdf, 0x29, 0xcd, 0x83, 0x51, 0xc9, 0xaf, 0x50, 0x8d, 0x59,
	0x68, 0x86, 0xbc, 0x5f, 0x3a, 0xe4, 0xe7, 0x2c, 0xf4, 0x64, 0x94, 0xf3, 0x37, 0xb4, 0xcd, 0xe7,
	0xd6, 0xe4, 0xfe, 0x9d, 0x05, 0xf6, 0x39, 0x0b, 0x67, 0x50, 0x5b, 0x8b, 0x50, 0xe3, 0x8a, 0x33,
	0xf7, 0x01, 0x65, 0x72, 0x0c, 0x76, 0xcc, 0x42, 0x5d, 0xde, 0xde, 0xb2, 0xf2, 0xf0, 0xf7, 0x5f,
	0x2a, 0xf8, 0xd4, 0xc3, 0xe8, 0xc1, 0xef, 0xd0, 0x34, 0x06, 0x2c, 0xe1, 0x86, 0x4e, 0xcd, 0x12,
	0xbc, 0xa1, 0x53, 0x84, 0xe8, 0x8d, 0x1f, 0x17, 0xe6, 0x3b, 0x4a, 0xf9, 0xab, 0xf2, 0x87, 0xe5,
	0x7c, 0x54, 0xeb, 0xf1, 0x7f, 0x96, 0x8b, 0xc7, 0xb4, 0x1e, 0x67, 0x9c, 0xd7, 0xe7, 0x38, 0xd7,
	0x2b, 0x50, 0xf5, 0xb2, 0xfe, 0x0a, 0x7c, 0xc9, 0x72, 0xb1, 0x7a, 0x05, 0xca, 0x2f, 0xa8, 0x38,
	0x67, 0x00, 0x55, 0x54, 0xcb, 0xd8, 0x75, 0xde, 0x57, 0xa0, 0x7b, 0x46, 0x05, 0x0e, 0xd3, 0x63,
	0xc7, 0x16, 0x2b, 0x8f, 0x59, 0xa8, 0x12, 0xf5, 0xcb, 0x13, 0xb3, 0x50, 0x26, 0x68, 0x17, 0xe2,
	0xa1, 0xaf, 0x3a, 0xba, 0x24, 0x2a, 0x43, 0xe8, 0xa0, 0x6b, 0xd6, 0xb3, 0xba, 0xec, 0x10, 0xb3,
	0xf0, 0x4a, 0xb5, 0xed, 0xa4, 0xd0, 0x36, 0x10, 0xad, 0x49, 0xd9, 0x37, 0xdd, 0xe7, 0xa3, 0xb7,
	0x55, 0x80, 0xa7, 0x2a, 0xe2, 0x24, 0x8b, 0xc8, 0x08, 0xea, 0xea, 0xff, 0x03, 0x71, 0x4a, 0x13,
	0x17, 0xfe, 0x6d, 0x0c, 0x86, 0x2b, 0x63, 0xb2, 0x78, 0xea, 0x6c, 0x90, 0x4b, 0x68, 0xe8, 0x77,
	0x98, 0xec, 0x97, 0x86, 0x2f, 0xfe, 0x1b, 0x19, 0xec, 0xad, 0x0e, 0x52, 0x87, 0x3e, 0x07, 0xb8,
	0x7b, 0x85, 0xc8, 0xcf, 0xa5, 0x29, 0xf7, 0x1e, 0xe2, 0xc1, 0x4f, 0x0f, 0xc6, 0xa9, 0xd3, 0x47,
	0x50, 0x57, 0x3b, 0x6e, 0x09, 0x08, 0x0b, 0xfb, 0x76, 0x09, 0x08, 0x73, 0x4b, 0x72, 0x06, 0x82,
	0x1c, 0x81, 0xa5, 0x20, 0xcc, 0xed, 0x9c, 0xe5, 0x20, 0xcc, 0x2e, 0xb3, 0x2a, 0x53, 0x8d, 0xca,
	0x92, 0x32, 0x17, 0xae, 0xda, 0x92, 0x32, 0xe7, 0x66, 0xcd, 0xd9, 0x38, 0xfd, 0x0d, 0x76, 0x22,
	0xe6, 0xa2, 0xcf, 0xa5, 0xb7, 0x7e, 0x92, 0xc5, 0x34, 0x77, 0x39, 0x2b, 0x04, 0x0d, 0x8b, 0x28,
	0xa0, 0xa7, 0x3d, 0x0f, 0xe5, 0x33, 0x94, 0x47, 0xf8, 0xbe, 0x8e, 0xac, 0xeb, 0xba, 0x7c, 0x68,
	0x8f, 0xbf, 0x04, 0x00, 0x00, 0xff, 0xff, 0x70, 0x99, 0xcc, 0x10, 0xda, 0x0a, 0x00, 0x00,
}
