// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor_api_grpc_pb.proto

package monitor_api_grpc_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_7f3730e73fb744ea, []int{0}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_7f3730e73fb744ea, []int{1}
}
func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (dst *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(dst, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//
// Node
//
type GetNodeRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,5,opt,name=project_role_name,json=projectRoleName" json:"project_role_name,omitempty"`
	Target               string   `protobuf:"bytes,6,opt,name=target" json:"target,omitempty"`
	Cluster              string   `protobuf:"bytes,7,opt,name=cluster" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRequest) Reset()         { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()    {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_7f3730e73fb744ea, []int{2}
}
func (m *GetNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRequest.Unmarshal(m, b)
}
func (m *GetNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRequest.Marshal(b, m, deterministic)
}
func (dst *GetNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRequest.Merge(dst, src)
}
func (m *GetNodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRequest.Size(m)
}
func (m *GetNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRequest proto.InternalMessageInfo

func (m *GetNodeRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetNodeRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetNodeRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *GetNodeRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetNodeRequest) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

func (m *GetNodeRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *GetNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type GetNodeReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeReply) Reset()         { *m = GetNodeReply{} }
func (m *GetNodeReply) String() string { return proto.CompactTextString(m) }
func (*GetNodeReply) ProtoMessage()    {}
func (*GetNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_7f3730e73fb744ea, []int{3}
}
func (m *GetNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeReply.Unmarshal(m, b)
}
func (m *GetNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeReply.Marshal(b, m, deterministic)
}
func (dst *GetNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeReply.Merge(dst, src)
}
func (m *GetNodeReply) XXX_Size() int {
	return xxx_messageInfo_GetNodeReply.Size(m)
}
func (m *GetNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeReply proto.InternalMessageInfo

func (m *GetNodeReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetNodeReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetNodeReply) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type UpdateNodeRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role" json:"role,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	StatusReason         string   `protobuf:"bytes,6,opt,name=status_reason,json=statusReason" json:"status_reason,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=state" json:"state,omitempty"`
	StateReason          string   `protobuf:"bytes,8,opt,name=state_reason,json=stateReason" json:"state_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeRequest) Reset()         { *m = UpdateNodeRequest{} }
func (m *UpdateNodeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeRequest) ProtoMessage()    {}
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_7f3730e73fb744ea, []int{4}
}
func (m *UpdateNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeRequest.Unmarshal(m, b)
}
func (m *UpdateNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeRequest.Merge(dst, src)
}
func (m *UpdateNodeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeRequest.Size(m)
}
func (m *UpdateNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeRequest proto.InternalMessageInfo

func (m *UpdateNodeRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *UpdateNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateNodeRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *UpdateNodeRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UpdateNodeRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateNodeRequest) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *UpdateNodeRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *UpdateNodeRequest) GetStateReason() string {
	if m != nil {
		return m.StateReason
	}
	return ""
}

type UpdateNodeReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeReply) Reset()         { *m = UpdateNodeReply{} }
func (m *UpdateNodeReply) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeReply) ProtoMessage()    {}
func (*UpdateNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_7f3730e73fb744ea, []int{5}
}
func (m *UpdateNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeReply.Unmarshal(m, b)
}
func (m *UpdateNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeReply.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeReply.Merge(dst, src)
}
func (m *UpdateNodeReply) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeReply.Size(m)
}
func (m *UpdateNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeReply proto.InternalMessageInfo

func (m *UpdateNodeReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *UpdateNodeReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Node struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Cluster              string               `protobuf:"bytes,3,opt,name=cluster" json:"cluster,omitempty"`
	Name                 string               `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Kind                 string               `protobuf:"bytes,5,opt,name=kind" json:"kind,omitempty"`
	Role                 string               `protobuf:"bytes,6,opt,name=role" json:"role,omitempty"`
	Status               string               `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
	StatusReason         string               `protobuf:"bytes,8,opt,name=status_reason,json=statusReason" json:"status_reason,omitempty"`
	State                string               `protobuf:"bytes,9,opt,name=state" json:"state,omitempty"`
	StateReason          string               `protobuf:"bytes,10,opt,name=state_reason,json=stateReason" json:"state_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_7f3730e73fb744ea, []int{6}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Node) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Node) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Node) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Node) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Node) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *Node) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Node) GetStateReason() string {
	if m != nil {
		return m.StateReason
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "monitor_api_grpc_pb.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "monitor_api_grpc_pb.StatusReply")
	proto.RegisterType((*GetNodeRequest)(nil), "monitor_api_grpc_pb.GetNodeRequest")
	proto.RegisterType((*GetNodeReply)(nil), "monitor_api_grpc_pb.GetNodeReply")
	proto.RegisterType((*UpdateNodeRequest)(nil), "monitor_api_grpc_pb.UpdateNodeRequest")
	proto.RegisterType((*UpdateNodeReply)(nil), "monitor_api_grpc_pb.UpdateNodeReply")
	proto.RegisterType((*Node)(nil), "monitor_api_grpc_pb.Node")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorApiClient is the client API for MonitorApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorApiClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeReply, error)
}

type monitorApiClient struct {
	cc *grpc.ClientConn
}

func NewMonitorApiClient(cc *grpc.ClientConn) MonitorApiClient {
	return &monitorApiClient{cc}
}

func (c *monitorApiClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error) {
	out := new(GetNodeReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeReply, error) {
	out := new(UpdateNodeReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/UpdateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorApiServer is the server API for MonitorApi service.
type MonitorApiServer interface {
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeReply, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeReply, error)
}

func RegisterMonitorApiServer(s *grpc.Server, srv MonitorApiServer) {
	s.RegisterService(&_MonitorApi_serviceDesc, srv)
}

func _MonitorApi_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/UpdateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor_api_grpc_pb.MonitorApi",
	HandlerType: (*MonitorApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _MonitorApi_Status_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _MonitorApi_GetNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _MonitorApi_UpdateNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor_api_grpc_pb.proto",
}

func init() {
	proto.RegisterFile("monitor_api_grpc_pb.proto", fileDescriptor_monitor_api_grpc_pb_7f3730e73fb744ea)
}

var fileDescriptor_monitor_api_grpc_pb_7f3730e73fb744ea = []byte{
	// 578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0x12, 0xe7, 0xf7, 0xa6, 0xfd, 0x42, 0x07, 0x84, 0x9c, 0x74, 0x91, 0xd4, 0x45, 0xa8,
	0x62, 0xe1, 0xa0, 0xb0, 0x62, 0x99, 0x82, 0x54, 0xb1, 0xa0, 0x8a, 0x5c, 0xd8, 0x21, 0x59, 0x13,
	0xfb, 0x62, 0x19, 0xec, 0xcc, 0x30, 0x33, 0x96, 0xe8, 0x63, 0xf0, 0x56, 0x3c, 0x06, 0x2b, 0x9e,
	0x03, 0xcd, 0x8f, 0xdb, 0x46, 0xb5, 0x52, 0xc4, 0xee, 0xfe, 0x9c, 0x7b, 0x93, 0x7b, 0xce, 0xf1,
	0xc0, 0xa4, 0x64, 0xdb, 0x5c, 0x31, 0x11, 0x53, 0x9e, 0xc7, 0x99, 0xe0, 0x49, 0xcc, 0x37, 0x21,
	0x17, 0x4c, 0x31, 0xf2, 0xb8, 0xa1, 0x35, 0x9d, 0x65, 0x8c, 0x65, 0x05, 0x2e, 0x0c, 0x64, 0x53,
	0x7d, 0x5e, 0xa8, 0xbc, 0x44, 0xa9, 0x68, 0xc9, 0xed, 0x54, 0x30, 0x86, 0xc3, 0x2b, 0x45, 0x55,
	0x25, 0x23, 0xfc, 0x56, 0xa1, 0x54, 0xc1, 0x0c, 0x46, 0x75, 0x81, 0x17, 0xd7, 0xe4, 0x11, 0x78,
	0xa5, 0xcc, 0xfc, 0xd6, 0xbc, 0x75, 0x36, 0x8c, 0x74, 0x18, 0xfc, 0x6e, 0xc1, 0xff, 0x17, 0xa8,
	0x2e, 0x59, 0x8a, 0x6e, 0x86, 0x4c, 0x60, 0xa0, 0x04, 0x4d, 0x30, 0xce, 0x53, 0x87, 0xec, 0x9b,
	0xfc, 0x5d, 0x4a, 0x8e, 0x61, 0x58, 0x49, 0x14, 0xf1, 0x96, 0x96, 0xe8, 0xb7, 0x4d, 0x6f, 0xa0,
	0x0b, 0x97, 0xb4, 0x44, 0xdd, 0x14, 0xac, 0x40, 0xdb, 0xf4, 0x6c, 0x53, 0x17, 0x4c, 0xf3, 0x04,
	0x0e, 0xb8, 0x60, 0x5f, 0x30, 0x51, 0xb6, 0xdf, 0x31, 0xfd, 0x91, 0xab, 0x19, 0xc8, 0x0b, 0x38,
	0xaa, 0x21, 0xb7, 0x7b, 0xba, 0x06, 0x37, 0x76, 0x8d, 0xa8, 0x5e, 0xf7, 0x14, 0x7a, 0x8a, 0x8a,
	0x0c, 0x95, 0xdf, 0x33, 0x00, 0x97, 0x11, 0x1f, 0xfa, 0x49, 0x51, 0x49, 0x85, 0xc2, 0xef, 0xdb,
	0xbf, 0xee, 0xd2, 0x40, 0xc0, 0xc1, 0xcd, 0x9d, 0x9a, 0x8a, 0x19, 0x8c, 0xa4, 0x61, 0x26, 0x4e,
	0x58, 0x8a, 0xe6, 0x50, 0x2f, 0x02, 0x5b, 0x7a, 0xc3, 0x52, 0xd4, 0x5c, 0xa1, 0x10, 0xee, 0x4a,
	0x1d, 0x92, 0x05, 0x74, 0xb7, 0x2c, 0x45, 0xe9, 0x7b, 0x73, 0xef, 0x6c, 0xb4, 0x9c, 0x84, 0x4d,
	0xf2, 0x99, 0x5f, 0xb0, 0xb8, 0xe0, 0x57, 0x0b, 0x8e, 0x3e, 0xf2, 0x94, 0x2a, 0xfc, 0x4b, 0x7e,
	0x09, 0x74, 0xee, 0x50, 0x6b, 0x62, 0x5d, 0xfb, 0x9a, 0x6f, 0x53, 0xc7, 0xa8, 0x89, 0x75, 0x4d,
	0x53, 0xe4, 0x58, 0x34, 0xb1, 0xa6, 0xc4, 0xfe, 0x7b, 0xc7, 0x99, 0xcb, 0xc8, 0x29, 0x1c, 0xba,
	0x43, 0x05, 0x52, 0xc9, 0xb6, 0x8e, 0xb1, 0x03, 0xe9, 0x7c, 0xa1, 0x6b, 0xe4, 0x09, 0x74, 0x75,
	0x8e, 0x8e, 0x35, 0x9b, 0x68, 0xd1, 0x4c, 0x50, 0x4f, 0x0e, 0xac, 0x68, 0xa6, 0x66, 0x07, 0x83,
	0xb7, 0x30, 0xbe, 0x7b, 0xe1, 0xbf, 0x31, 0x1b, 0xfc, 0x6c, 0x43, 0x47, 0x2f, 0x20, 0xaf, 0x01,
	0x2a, 0xb3, 0x2e, 0x8d, 0xa9, 0x32, 0xa3, 0xa3, 0xe5, 0x34, 0xb4, 0xb6, 0x0f, 0x6b, 0xdb, 0x87,
	0x1f, 0x6a, 0xdb, 0x47, 0x43, 0x87, 0x5e, 0x29, 0x3d, 0x9a, 0x08, 0xac, 0x47, 0xdb, 0x0f, 0x8f,
	0x3a, 0xf4, 0x6a, 0xc7, 0x35, 0xde, 0x8e, 0x6b, 0x6e, 0x04, 0xe9, 0x34, 0x08, 0xd2, 0x6d, 0x10,
	0xa4, 0xd7, 0x28, 0x48, 0x7f, 0xbf, 0x20, 0x83, 0x7d, 0x82, 0x0c, 0xf7, 0x09, 0x02, 0xf7, 0x04,
	0x59, 0xfe, 0x68, 0x03, 0xbc, 0xb7, 0xbe, 0x5c, 0xf1, 0x9c, 0xac, 0xa1, 0x67, 0x1f, 0x00, 0x12,
	0x34, 0xda, 0x75, 0xe7, 0xb9, 0x98, 0xce, 0xf7, 0x62, 0x78, 0x71, 0x1d, 0xfc, 0x47, 0xae, 0xa0,
	0xef, 0x3e, 0x24, 0x72, 0xda, 0x08, 0xdf, 0x7d, 0x4e, 0xa6, 0x27, 0xfb, 0x41, 0x76, 0xe9, 0x27,
	0x80, 0x5b, 0x1b, 0x91, 0xe7, 0x8d, 0x23, 0xf7, 0xbe, 0xa4, 0xe9, 0xb3, 0x07, 0x71, 0x66, 0xfb,
	0xf9, 0x4b, 0x38, 0xce, 0x59, 0xa8, 0xfb, 0x21, 0x7e, 0xa7, 0x25, 0x2f, 0x50, 0x86, 0x82, 0x55,
	0x0a, 0xb3, 0x2a, 0x4f, 0xf1, 0x7c, 0x1c, 0xe9, 0xf8, 0x42, 0xc7, 0x6b, 0xed, 0x93, 0x75, 0x6b,
	0xd3, 0x33, 0x86, 0x79, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x06, 0xc7, 0xf0, 0x52, 0xa2, 0x05,
	0x00, 0x00,
}
