// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor_api_grpc_pb.proto

package monitor_api_grpc_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{0}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{1}
}
func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (dst *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(dst, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//
// Node
//
type GetNodeRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,5,opt,name=project_role_name,json=projectRoleName" json:"project_role_name,omitempty"`
	Target               string   `protobuf:"bytes,6,opt,name=target" json:"target,omitempty"`
	Cluster              string   `protobuf:"bytes,7,opt,name=cluster" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRequest) Reset()         { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()    {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{2}
}
func (m *GetNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRequest.Unmarshal(m, b)
}
func (m *GetNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRequest.Marshal(b, m, deterministic)
}
func (dst *GetNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRequest.Merge(dst, src)
}
func (m *GetNodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRequest.Size(m)
}
func (m *GetNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRequest proto.InternalMessageInfo

func (m *GetNodeRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetNodeRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetNodeRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *GetNodeRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetNodeRequest) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

func (m *GetNodeRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *GetNodeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type GetNodeReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,3,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeReply) Reset()         { *m = GetNodeReply{} }
func (m *GetNodeReply) String() string { return proto.CompactTextString(m) }
func (*GetNodeReply) ProtoMessage()    {}
func (*GetNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{3}
}
func (m *GetNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeReply.Unmarshal(m, b)
}
func (m *GetNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeReply.Marshal(b, m, deterministic)
}
func (dst *GetNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeReply.Merge(dst, src)
}
func (m *GetNodeReply) XXX_Size() int {
	return xxx_messageInfo_GetNodeReply.Size(m)
}
func (m *GetNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeReply proto.InternalMessageInfo

func (m *GetNodeReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetNodeReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetNodeReply) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type UpdateNodeRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role" json:"role,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	StatusReason         string   `protobuf:"bytes,6,opt,name=status_reason,json=statusReason" json:"status_reason,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=state" json:"state,omitempty"`
	StateReason          string   `protobuf:"bytes,8,opt,name=state_reason,json=stateReason" json:"state_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeRequest) Reset()         { *m = UpdateNodeRequest{} }
func (m *UpdateNodeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeRequest) ProtoMessage()    {}
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{4}
}
func (m *UpdateNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeRequest.Unmarshal(m, b)
}
func (m *UpdateNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeRequest.Merge(dst, src)
}
func (m *UpdateNodeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeRequest.Size(m)
}
func (m *UpdateNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeRequest proto.InternalMessageInfo

func (m *UpdateNodeRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *UpdateNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateNodeRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *UpdateNodeRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UpdateNodeRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateNodeRequest) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *UpdateNodeRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *UpdateNodeRequest) GetStateReason() string {
	if m != nil {
		return m.StateReason
	}
	return ""
}

type UpdateNodeReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeReply) Reset()         { *m = UpdateNodeReply{} }
func (m *UpdateNodeReply) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeReply) ProtoMessage()    {}
func (*UpdateNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{5}
}
func (m *UpdateNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeReply.Unmarshal(m, b)
}
func (m *UpdateNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeReply.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeReply.Merge(dst, src)
}
func (m *UpdateNodeReply) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeReply.Size(m)
}
func (m *UpdateNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeReply proto.InternalMessageInfo

func (m *UpdateNodeReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *UpdateNodeReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Node struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Cluster              string               `protobuf:"bytes,3,opt,name=cluster" json:"cluster,omitempty"`
	Name                 string               `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Kind                 string               `protobuf:"bytes,5,opt,name=kind" json:"kind,omitempty"`
	Role                 string               `protobuf:"bytes,6,opt,name=role" json:"role,omitempty"`
	Status               string               `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
	StatusReason         string               `protobuf:"bytes,8,opt,name=status_reason,json=statusReason" json:"status_reason,omitempty"`
	State                string               `protobuf:"bytes,9,opt,name=state" json:"state,omitempty"`
	StateReason          string               `protobuf:"bytes,10,opt,name=state_reason,json=stateReason" json:"state_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{6}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Node) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Node) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Node) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Node) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Node) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *Node) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Node) GetStateReason() string {
	if m != nil {
		return m.StateReason
	}
	return ""
}

//
// Report
//
type ReportRequest struct {
	Index                string    `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Project              string    `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
	Kind                 string    `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
	Host                 string    `protobuf:"bytes,4,opt,name=host" json:"host,omitempty"`
	State                int64     `protobuf:"varint,5,opt,name=state" json:"state,omitempty"`
	Warning              string    `protobuf:"bytes,6,opt,name=warning" json:"warning,omitempty"`
	Warnings             int64     `protobuf:"varint,7,opt,name=warnings" json:"warnings,omitempty"`
	Error                string    `protobuf:"bytes,8,opt,name=error" json:"error,omitempty"`
	Errors               int64     `protobuf:"varint,9,opt,name=errors" json:"errors,omitempty"`
	Timestamp            int64     `protobuf:"varint,10,opt,name=timestamp" json:"timestamp,omitempty"`
	Logs                 []*Log    `protobuf:"bytes,11,rep,name=logs" json:"logs,omitempty"`
	Metrics              []*Metric `protobuf:"bytes,12,rep,name=metrics" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{7}
}
func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (dst *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(dst, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ReportRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *ReportRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ReportRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ReportRequest) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ReportRequest) GetWarning() string {
	if m != nil {
		return m.Warning
	}
	return ""
}

func (m *ReportRequest) GetWarnings() int64 {
	if m != nil {
		return m.Warnings
	}
	return 0
}

func (m *ReportRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ReportRequest) GetErrors() int64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

func (m *ReportRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ReportRequest) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *ReportRequest) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type ReportReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportReply) Reset()         { *m = ReportReply{} }
func (m *ReportReply) String() string { return proto.CompactTextString(m) }
func (*ReportReply) ProtoMessage()    {}
func (*ReportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{8}
}
func (m *ReportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportReply.Unmarshal(m, b)
}
func (m *ReportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportReply.Marshal(b, m, deterministic)
}
func (dst *ReportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportReply.Merge(dst, src)
}
func (m *ReportReply) XXX_Size() int {
	return xxx_messageInfo_ReportReply.Size(m)
}
func (m *ReportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReportReply proto.InternalMessageInfo

func (m *ReportReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ReportReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Log struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Time                 string            `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	Log                  map[string]string `protobuf:"bytes,3,rep,name=log" json:"log,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{9}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (dst *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(dst, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Log) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Log) GetLog() map[string]string {
	if m != nil {
		return m.Log
	}
	return nil
}

type Metric struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Time                 string            `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	Tag                  map[string]string `protobuf:"bytes,3,rep,name=tag" json:"tag,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metric               map[string]int64  `protobuf:"bytes,4,rep,name=metric" json:"metric,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{10}
}
func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (dst *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(dst, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metric) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Metric) GetTag() map[string]string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *Metric) GetMetric() map[string]int64 {
	if m != nil {
		return m.Metric
	}
	return nil
}

//
// GetUserState
//
type GetUserStateRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,5,opt,name=project_role_name,json=projectRoleName" json:"project_role_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserStateRequest) Reset()         { *m = GetUserStateRequest{} }
func (m *GetUserStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserStateRequest) ProtoMessage()    {}
func (*GetUserStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{11}
}
func (m *GetUserStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserStateRequest.Unmarshal(m, b)
}
func (m *GetUserStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserStateRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserStateRequest.Merge(dst, src)
}
func (m *GetUserStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserStateRequest.Size(m)
}
func (m *GetUserStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserStateRequest proto.InternalMessageInfo

func (m *GetUserStateRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetUserStateRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetUserStateRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *GetUserStateRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetUserStateRequest) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

type GetUserStateReply struct {
	StatusCode           int64             `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string            `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	IndexMap             map[string]*Index `protobuf:"bytes,3,rep,name=index_map,json=indexMap" json:"index_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetUserStateReply) Reset()         { *m = GetUserStateReply{} }
func (m *GetUserStateReply) String() string { return proto.CompactTextString(m) }
func (*GetUserStateReply) ProtoMessage()    {}
func (*GetUserStateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{12}
}
func (m *GetUserStateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserStateReply.Unmarshal(m, b)
}
func (m *GetUserStateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserStateReply.Marshal(b, m, deterministic)
}
func (dst *GetUserStateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserStateReply.Merge(dst, src)
}
func (m *GetUserStateReply) XXX_Size() int {
	return xxx_messageInfo_GetUserStateReply.Size(m)
}
func (m *GetUserStateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserStateReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserStateReply proto.InternalMessageInfo

func (m *GetUserStateReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetUserStateReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetUserStateReply) GetIndexMap() map[string]*Index {
	if m != nil {
		return m.IndexMap
	}
	return nil
}

//
// GetIndexState
//
type GetIndexStateRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,5,opt,name=project_role_name,json=projectRoleName" json:"project_role_name,omitempty"`
	Index                string   `protobuf:"bytes,6,opt,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIndexStateRequest) Reset()         { *m = GetIndexStateRequest{} }
func (m *GetIndexStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetIndexStateRequest) ProtoMessage()    {}
func (*GetIndexStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{13}
}
func (m *GetIndexStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexStateRequest.Unmarshal(m, b)
}
func (m *GetIndexStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexStateRequest.Marshal(b, m, deterministic)
}
func (dst *GetIndexStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexStateRequest.Merge(dst, src)
}
func (m *GetIndexStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetIndexStateRequest.Size(m)
}
func (m *GetIndexStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexStateRequest proto.InternalMessageInfo

func (m *GetIndexStateRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetIndexStateRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetIndexStateRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *GetIndexStateRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetIndexStateRequest) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

func (m *GetIndexStateRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type GetIndexStateReply struct {
	StatusCode           int64            `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string           `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	HostMap              map[string]*Host `protobuf:"bytes,3,rep,name=host_map,json=hostMap" json:"host_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetIndexStateReply) Reset()         { *m = GetIndexStateReply{} }
func (m *GetIndexStateReply) String() string { return proto.CompactTextString(m) }
func (*GetIndexStateReply) ProtoMessage()    {}
func (*GetIndexStateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{14}
}
func (m *GetIndexStateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexStateReply.Unmarshal(m, b)
}
func (m *GetIndexStateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexStateReply.Marshal(b, m, deterministic)
}
func (dst *GetIndexStateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexStateReply.Merge(dst, src)
}
func (m *GetIndexStateReply) XXX_Size() int {
	return xxx_messageInfo_GetIndexStateReply.Size(m)
}
func (m *GetIndexStateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexStateReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexStateReply proto.InternalMessageInfo

func (m *GetIndexStateReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetIndexStateReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetIndexStateReply) GetHostMap() map[string]*Host {
	if m != nil {
		return m.HostMap
	}
	return nil
}

//
// GetIndex
//
type GetIndexRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,5,opt,name=project_role_name,json=projectRoleName" json:"project_role_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIndexRequest) Reset()         { *m = GetIndexRequest{} }
func (m *GetIndexRequest) String() string { return proto.CompactTextString(m) }
func (*GetIndexRequest) ProtoMessage()    {}
func (*GetIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{15}
}
func (m *GetIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexRequest.Unmarshal(m, b)
}
func (m *GetIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexRequest.Marshal(b, m, deterministic)
}
func (dst *GetIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexRequest.Merge(dst, src)
}
func (m *GetIndexRequest) XXX_Size() int {
	return xxx_messageInfo_GetIndexRequest.Size(m)
}
func (m *GetIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexRequest proto.InternalMessageInfo

func (m *GetIndexRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetIndexRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetIndexRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *GetIndexRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetIndexRequest) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

type GetIndexReply struct {
	StatusCode           int64             `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string            `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	IndexMap             map[string]*Index `protobuf:"bytes,3,rep,name=index_map,json=indexMap" json:"index_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetIndexReply) Reset()         { *m = GetIndexReply{} }
func (m *GetIndexReply) String() string { return proto.CompactTextString(m) }
func (*GetIndexReply) ProtoMessage()    {}
func (*GetIndexReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{16}
}
func (m *GetIndexReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexReply.Unmarshal(m, b)
}
func (m *GetIndexReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexReply.Marshal(b, m, deterministic)
}
func (dst *GetIndexReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexReply.Merge(dst, src)
}
func (m *GetIndexReply) XXX_Size() int {
	return xxx_messageInfo_GetIndexReply.Size(m)
}
func (m *GetIndexReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexReply proto.InternalMessageInfo

func (m *GetIndexReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetIndexReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetIndexReply) GetIndexMap() map[string]*Index {
	if m != nil {
		return m.IndexMap
	}
	return nil
}

type Index struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Count                float64  `protobuf:"fixed64,2,opt,name=count" json:"count,omitempty"`
	States               float64  `protobuf:"fixed64,3,opt,name=states" json:"states,omitempty"`
	Warnings             float64  `protobuf:"fixed64,4,opt,name=warnings" json:"warnings,omitempty"`
	Errors               float64  `protobuf:"fixed64,5,opt,name=errors" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{17}
}
func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (dst *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(dst, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Index) GetCount() float64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Index) GetStates() float64 {
	if m != nil {
		return m.States
	}
	return 0
}

func (m *Index) GetWarnings() float64 {
	if m != nil {
		return m.Warnings
	}
	return 0
}

func (m *Index) GetErrors() float64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

//
// GetHost
//
type GetHostRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,5,opt,name=project_role_name,json=projectRoleName" json:"project_role_name,omitempty"`
	Index                string   `protobuf:"bytes,6,opt,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostRequest) Reset()         { *m = GetHostRequest{} }
func (m *GetHostRequest) String() string { return proto.CompactTextString(m) }
func (*GetHostRequest) ProtoMessage()    {}
func (*GetHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{18}
}
func (m *GetHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostRequest.Unmarshal(m, b)
}
func (m *GetHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostRequest.Marshal(b, m, deterministic)
}
func (dst *GetHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostRequest.Merge(dst, src)
}
func (m *GetHostRequest) XXX_Size() int {
	return xxx_messageInfo_GetHostRequest.Size(m)
}
func (m *GetHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostRequest proto.InternalMessageInfo

func (m *GetHostRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetHostRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetHostRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *GetHostRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetHostRequest) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

func (m *GetHostRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type GetHostReply struct {
	StatusCode           int64            `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string           `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	HostMap              map[string]*Host `protobuf:"bytes,3,rep,name=host_map,json=hostMap" json:"host_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetHostReply) Reset()         { *m = GetHostReply{} }
func (m *GetHostReply) String() string { return proto.CompactTextString(m) }
func (*GetHostReply) ProtoMessage()    {}
func (*GetHostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{19}
}
func (m *GetHostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostReply.Unmarshal(m, b)
}
func (m *GetHostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostReply.Marshal(b, m, deterministic)
}
func (dst *GetHostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostReply.Merge(dst, src)
}
func (m *GetHostReply) XXX_Size() int {
	return xxx_messageInfo_GetHostReply.Size(m)
}
func (m *GetHostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostReply proto.InternalMessageInfo

func (m *GetHostReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetHostReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetHostReply) GetHostMap() map[string]*Host {
	if m != nil {
		return m.HostMap
	}
	return nil
}

type Host struct {
	Index                string   `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	State                float64  `protobuf:"fixed64,4,opt,name=state" json:"state,omitempty"`
	Error                string   `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
	Errors               float64  `protobuf:"fixed64,6,opt,name=errors" json:"errors,omitempty"`
	Warning              string   `protobuf:"bytes,7,opt,name=warning" json:"warning,omitempty"`
	Warnings             float64  `protobuf:"fixed64,8,opt,name=warnings" json:"warnings,omitempty"`
	Timestamp            float64  `protobuf:"fixed64,9,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{20}
}
func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (dst *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(dst, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Host) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetState() float64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Host) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Host) GetErrors() float64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

func (m *Host) GetWarning() string {
	if m != nil {
		return m.Warning
	}
	return ""
}

func (m *Host) GetWarnings() float64 {
	if m != nil {
		return m.Warnings
	}
	return 0
}

func (m *Host) GetTimestamp() float64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

//
// GetLog
//
type GetLogRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,4,opt,name=project_name,json=projectName" json:"project_name,omitempty"`
	ProjectRoleName      string   `protobuf:"bytes,5,opt,name=project_role_name,json=projectRoleName" json:"project_role_name,omitempty"`
	Index                string   `protobuf:"bytes,6,opt,name=index" json:"index,omitempty"`
	LogName              string   `protobuf:"bytes,7,opt,name=log_name,json=logName" json:"log_name,omitempty"`
	LogHost              string   `protobuf:"bytes,8,opt,name=log_host,json=logHost" json:"log_host,omitempty"`
	LogTraceId           string   `protobuf:"bytes,9,opt,name=log_trace_id,json=logTraceId" json:"log_trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogRequest) Reset()         { *m = GetLogRequest{} }
func (m *GetLogRequest) String() string { return proto.CompactTextString(m) }
func (*GetLogRequest) ProtoMessage()    {}
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{21}
}
func (m *GetLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogRequest.Unmarshal(m, b)
}
func (m *GetLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogRequest.Marshal(b, m, deterministic)
}
func (dst *GetLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogRequest.Merge(dst, src)
}
func (m *GetLogRequest) XXX_Size() int {
	return xxx_messageInfo_GetLogRequest.Size(m)
}
func (m *GetLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogRequest proto.InternalMessageInfo

func (m *GetLogRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetLogRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetLogRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *GetLogRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetLogRequest) GetProjectRoleName() string {
	if m != nil {
		return m.ProjectRoleName
	}
	return ""
}

func (m *GetLogRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *GetLogRequest) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *GetLogRequest) GetLogHost() string {
	if m != nil {
		return m.LogHost
	}
	return ""
}

func (m *GetLogRequest) GetLogTraceId() string {
	if m != nil {
		return m.LogTraceId
	}
	return ""
}

type GetLogReply struct {
	StatusCode           int64    `protobuf:"varint,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,3,rep,name=logs" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogReply) Reset()         { *m = GetLogReply{} }
func (m *GetLogReply) String() string { return proto.CompactTextString(m) }
func (*GetLogReply) ProtoMessage()    {}
func (*GetLogReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850, []int{22}
}
func (m *GetLogReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogReply.Unmarshal(m, b)
}
func (m *GetLogReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogReply.Marshal(b, m, deterministic)
}
func (dst *GetLogReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogReply.Merge(dst, src)
}
func (m *GetLogReply) XXX_Size() int {
	return xxx_messageInfo_GetLogReply.Size(m)
}
func (m *GetLogReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogReply proto.InternalMessageInfo

func (m *GetLogReply) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetLogReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetLogReply) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "monitor_api_grpc_pb.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "monitor_api_grpc_pb.StatusReply")
	proto.RegisterType((*GetNodeRequest)(nil), "monitor_api_grpc_pb.GetNodeRequest")
	proto.RegisterType((*GetNodeReply)(nil), "monitor_api_grpc_pb.GetNodeReply")
	proto.RegisterType((*UpdateNodeRequest)(nil), "monitor_api_grpc_pb.UpdateNodeRequest")
	proto.RegisterType((*UpdateNodeReply)(nil), "monitor_api_grpc_pb.UpdateNodeReply")
	proto.RegisterType((*Node)(nil), "monitor_api_grpc_pb.Node")
	proto.RegisterType((*ReportRequest)(nil), "monitor_api_grpc_pb.ReportRequest")
	proto.RegisterType((*ReportReply)(nil), "monitor_api_grpc_pb.ReportReply")
	proto.RegisterType((*Log)(nil), "monitor_api_grpc_pb.Log")
	proto.RegisterMapType((map[string]string)(nil), "monitor_api_grpc_pb.Log.LogEntry")
	proto.RegisterType((*Metric)(nil), "monitor_api_grpc_pb.Metric")
	proto.RegisterMapType((map[string]int64)(nil), "monitor_api_grpc_pb.Metric.MetricEntry")
	proto.RegisterMapType((map[string]string)(nil), "monitor_api_grpc_pb.Metric.TagEntry")
	proto.RegisterType((*GetUserStateRequest)(nil), "monitor_api_grpc_pb.GetUserStateRequest")
	proto.RegisterType((*GetUserStateReply)(nil), "monitor_api_grpc_pb.GetUserStateReply")
	proto.RegisterMapType((map[string]*Index)(nil), "monitor_api_grpc_pb.GetUserStateReply.IndexMapEntry")
	proto.RegisterType((*GetIndexStateRequest)(nil), "monitor_api_grpc_pb.GetIndexStateRequest")
	proto.RegisterType((*GetIndexStateReply)(nil), "monitor_api_grpc_pb.GetIndexStateReply")
	proto.RegisterMapType((map[string]*Host)(nil), "monitor_api_grpc_pb.GetIndexStateReply.HostMapEntry")
	proto.RegisterType((*GetIndexRequest)(nil), "monitor_api_grpc_pb.GetIndexRequest")
	proto.RegisterType((*GetIndexReply)(nil), "monitor_api_grpc_pb.GetIndexReply")
	proto.RegisterMapType((map[string]*Index)(nil), "monitor_api_grpc_pb.GetIndexReply.IndexMapEntry")
	proto.RegisterType((*Index)(nil), "monitor_api_grpc_pb.Index")
	proto.RegisterType((*GetHostRequest)(nil), "monitor_api_grpc_pb.GetHostRequest")
	proto.RegisterType((*GetHostReply)(nil), "monitor_api_grpc_pb.GetHostReply")
	proto.RegisterMapType((map[string]*Host)(nil), "monitor_api_grpc_pb.GetHostReply.HostMapEntry")
	proto.RegisterType((*Host)(nil), "monitor_api_grpc_pb.Host")
	proto.RegisterType((*GetLogRequest)(nil), "monitor_api_grpc_pb.GetLogRequest")
	proto.RegisterType((*GetLogReply)(nil), "monitor_api_grpc_pb.GetLogReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorApiClient is the client API for MonitorApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorApiClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeReply, error)
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportReply, error)
	GetUserState(ctx context.Context, in *GetUserStateRequest, opts ...grpc.CallOption) (*GetUserStateReply, error)
	GetIndexState(ctx context.Context, in *GetIndexStateRequest, opts ...grpc.CallOption) (*GetIndexStateReply, error)
	GetIndex(ctx context.Context, in *GetIndexRequest, opts ...grpc.CallOption) (*GetIndexReply, error)
	GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostReply, error)
	GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogReply, error)
}

type monitorApiClient struct {
	cc *grpc.ClientConn
}

func NewMonitorApiClient(cc *grpc.ClientConn) MonitorApiClient {
	return &monitorApiClient{cc}
}

func (c *monitorApiClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error) {
	out := new(GetNodeReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeReply, error) {
	out := new(UpdateNodeReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/UpdateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportReply, error) {
	out := new(ReportReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) GetUserState(ctx context.Context, in *GetUserStateRequest, opts ...grpc.CallOption) (*GetUserStateReply, error) {
	out := new(GetUserStateReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/GetUserState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) GetIndexState(ctx context.Context, in *GetIndexStateRequest, opts ...grpc.CallOption) (*GetIndexStateReply, error) {
	out := new(GetIndexStateReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/GetIndexState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) GetIndex(ctx context.Context, in *GetIndexRequest, opts ...grpc.CallOption) (*GetIndexReply, error) {
	out := new(GetIndexReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/GetIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostReply, error) {
	out := new(GetHostReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/GetHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorApiClient) GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogReply, error) {
	out := new(GetLogReply)
	err := c.cc.Invoke(ctx, "/monitor_api_grpc_pb.MonitorApi/GetLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorApiServer is the server API for MonitorApi service.
type MonitorApiServer interface {
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeReply, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeReply, error)
	Report(context.Context, *ReportRequest) (*ReportReply, error)
	GetUserState(context.Context, *GetUserStateRequest) (*GetUserStateReply, error)
	GetIndexState(context.Context, *GetIndexStateRequest) (*GetIndexStateReply, error)
	GetIndex(context.Context, *GetIndexRequest) (*GetIndexReply, error)
	GetHost(context.Context, *GetHostRequest) (*GetHostReply, error)
	GetLog(context.Context, *GetLogRequest) (*GetLogReply, error)
}

func RegisterMonitorApiServer(s *grpc.Server, srv MonitorApiServer) {
	s.RegisterService(&_MonitorApi_serviceDesc, srv)
}

func _MonitorApi_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/UpdateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_GetUserState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).GetUserState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/GetUserState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).GetUserState(ctx, req.(*GetUserStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_GetIndexState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).GetIndexState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/GetIndexState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).GetIndexState(ctx, req.(*GetIndexStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_GetIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).GetIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/GetIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).GetIndex(ctx, req.(*GetIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/GetHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).GetHost(ctx, req.(*GetHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorApi_GetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorApiServer).GetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_api_grpc_pb.MonitorApi/GetLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorApiServer).GetLog(ctx, req.(*GetLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor_api_grpc_pb.MonitorApi",
	HandlerType: (*MonitorApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _MonitorApi_Status_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _MonitorApi_GetNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _MonitorApi_UpdateNode_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _MonitorApi_Report_Handler,
		},
		{
			MethodName: "GetUserState",
			Handler:    _MonitorApi_GetUserState_Handler,
		},
		{
			MethodName: "GetIndexState",
			Handler:    _MonitorApi_GetIndexState_Handler,
		},
		{
			MethodName: "GetIndex",
			Handler:    _MonitorApi_GetIndex_Handler,
		},
		{
			MethodName: "GetHost",
			Handler:    _MonitorApi_GetHost_Handler,
		},
		{
			MethodName: "GetLog",
			Handler:    _MonitorApi_GetLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor_api_grpc_pb.proto",
}

func init() {
	proto.RegisterFile("monitor_api_grpc_pb.proto", fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850)
}

var fileDescriptor_monitor_api_grpc_pb_fb89457a9e051850 = []byte{
	// 1317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xce, 0x78, 0xfc, 0x5b, 0x76, 0x08, 0xe9, 0x8d, 0x90, 0xe3, 0x20, 0x25, 0x99, 0x44, 0xbb,
	0x01, 0xa1, 0x49, 0x94, 0x85, 0x15, 0xcb, 0x05, 0xb2, 0x80, 0xb2, 0x91, 0x36, 0x4b, 0x98, 0x24,
	0x70, 0x41, 0xb2, 0x26, 0x76, 0x33, 0x3b, 0x64, 0xec, 0x1e, 0x7a, 0xda, 0xb0, 0x39, 0xf0, 0x22,
	0x88, 0x0b, 0x0f, 0xc0, 0x91, 0x03, 0x6f, 0x80, 0x38, 0xf1, 0x00, 0x1c, 0x90, 0x40, 0x1c, 0xb8,
	0x20, 0xf1, 0x04, 0xa8, 0xbb, 0xba, 0xc7, 0xe3, 0x64, 0xfc, 0x83, 0x0f, 0xa0, 0x1c, 0xa2, 0x74,
	0xfd, 0xf5, 0xcf, 0xf7, 0x55, 0xb5, 0xab, 0x07, 0x56, 0x7b, 0xac, 0x1f, 0x0a, 0xc6, 0xdb, 0x7e,
	0x1c, 0xb6, 0x03, 0x1e, 0x77, 0xda, 0xf1, 0x85, 0x1b, 0x73, 0x26, 0x18, 0xb9, 0x93, 0x63, 0x6a,
	0xad, 0x07, 0x8c, 0x05, 0x11, 0xdd, 0x55, 0x2e, 0x17, 0x83, 0x4f, 0x77, 0x45, 0xd8, 0xa3, 0x89,
	0xf0, 0x7b, 0x31, 0x46, 0x39, 0x4b, 0xb0, 0x78, 0x2a, 0x7c, 0x31, 0x48, 0x3c, 0xfa, 0xf9, 0x80,
	0x26, 0xc2, 0x59, 0x87, 0xba, 0x51, 0xc4, 0xd1, 0x15, 0x79, 0x11, 0xec, 0x5e, 0x12, 0x34, 0xad,
	0x0d, 0x6b, 0xa7, 0xe6, 0xc9, 0xa1, 0xf3, 0x87, 0x05, 0x2f, 0x1c, 0x52, 0xf1, 0x94, 0x75, 0xa9,
	0x8e, 0x21, 0xab, 0x50, 0x15, 0xdc, 0xef, 0xd0, 0x76, 0xd8, 0xd5, 0x9e, 0x15, 0x25, 0x1f, 0x75,
	0xc9, 0x1a, 0xd4, 0x06, 0x09, 0xe5, 0xed, 0xbe, 0xdf, 0xa3, 0xcd, 0x82, 0xb2, 0x55, 0xa5, 0xe2,
	0xa9, 0xdf, 0xa3, 0xd2, 0xc8, 0x59, 0x44, 0xd1, 0x68, 0xa3, 0x51, 0x2a, 0x94, 0x71, 0x13, 0x1a,
	0x31, 0x67, 0x9f, 0xd1, 0x8e, 0x40, 0x7b, 0x51, 0xd9, 0xeb, 0x5a, 0xa7, 0x5c, 0x5e, 0x85, 0x65,
	0xe3, 0x32, 0x9c, 0xa7, 0xa4, 0xfc, 0x96, 0xb4, 0xc1, 0x33, 0xd3, 0xbd, 0x04, 0x65, 0xe1, 0xf3,
	0x80, 0x8a, 0x66, 0x59, 0x39, 0x68, 0x89, 0x34, 0xa1, 0xd2, 0x89, 0x06, 0x89, 0xa0, 0xbc, 0x59,
	0xc1, 0xad, 0x6b, 0xd1, 0xe1, 0xd0, 0x48, 0xcf, 0x29, 0xa1, 0x58, 0x87, 0x7a, 0xa2, 0x90, 0x69,
	0x77, 0x58, 0x97, 0xaa, 0x83, 0xda, 0x1e, 0xa0, 0xea, 0x5d, 0xd6, 0xa5, 0x12, 0x2b, 0xca, 0xb9,
	0x3e, 0xa5, 0x1c, 0x92, 0x5d, 0x28, 0xf5, 0x59, 0x97, 0x26, 0x4d, 0x7b, 0xc3, 0xde, 0xa9, 0xef,
	0xaf, 0xba, 0x79, 0xf4, 0xa9, 0x15, 0xd0, 0xcf, 0xf9, 0xd5, 0x82, 0xe5, 0xf3, 0xb8, 0xeb, 0x0b,
	0x3a, 0x23, 0xbe, 0x04, 0x8a, 0x19, 0x68, 0xd5, 0x58, 0xea, 0x2e, 0xc3, 0x7e, 0x57, 0x23, 0xaa,
	0xc6, 0x52, 0x27, 0x21, 0xd2, 0x28, 0xaa, 0xb1, 0x84, 0x04, 0x77, 0xaf, 0x31, 0xd3, 0x12, 0xd9,
	0x82, 0x45, 0x7d, 0x50, 0x4e, 0xfd, 0x84, 0xf5, 0x35, 0x62, 0x8d, 0x44, 0xe7, 0x85, 0xd4, 0x91,
	0x15, 0x28, 0x49, 0x99, 0x6a, 0xd4, 0x50, 0x90, 0xa4, 0xa9, 0x81, 0x89, 0xac, 0x22, 0x69, 0x4a,
	0x87, 0x81, 0xce, 0x7b, 0xb0, 0x94, 0x3d, 0xe1, 0x7c, 0xc8, 0x3a, 0x3f, 0x16, 0xa0, 0x28, 0x27,
	0x20, 0x0f, 0x01, 0x06, 0x6a, 0xba, 0x6e, 0xdb, 0x17, 0x2a, 0xb4, 0xbe, 0xdf, 0x72, 0x31, 0xed,
	0x5d, 0x93, 0xf6, 0xee, 0x99, 0x49, 0x7b, 0xaf, 0xa6, 0xbd, 0x0f, 0x84, 0x0c, 0xed, 0x70, 0x6a,
	0x42, 0x0b, 0xd3, 0x43, 0xb5, 0xf7, 0xc1, 0x48, 0xd6, 0xd8, 0x23, 0x59, 0x93, 0x12, 0x52, 0xcc,
	0x21, 0xa4, 0x94, 0x43, 0x48, 0x39, 0x97, 0x90, 0xca, 0x64, 0x42, 0xaa, 0x93, 0x08, 0xa9, 0x4d,
	0x22, 0x04, 0x6e, 0x12, 0xf2, 0x7b, 0x01, 0x16, 0x3d, 0x1a, 0x33, 0x2e, 0x4c, 0xbe, 0xad, 0x40,
	0x29, 0xec, 0x77, 0xe9, 0x73, 0x9d, 0x6c, 0x28, 0xc8, 0x33, 0xeb, 0xa2, 0xd2, 0x44, 0x18, 0x71,
	0x5c, 0xc2, 0x3d, 0x63, 0x89, 0x30, 0x38, 0xc8, 0xf1, 0x70, 0x8b, 0x25, 0xc5, 0xb0, 0xde, 0x62,
	0x13, 0x2a, 0x5f, 0xfa, 0xbc, 0x1f, 0xf6, 0x03, 0x0d, 0x86, 0x11, 0x49, 0x0b, 0xaa, 0x7a, 0x88,
	0x88, 0xd8, 0x5e, 0x2a, 0xcb, 0xb9, 0x28, 0xe7, 0x8c, 0x6b, 0x2c, 0x50, 0x90, 0x08, 0xaa, 0x41,
	0xa2, 0x50, 0xb0, 0x3d, 0x2d, 0x91, 0x97, 0xa1, 0x96, 0xde, 0x7c, 0x0a, 0x03, 0xdb, 0x1b, 0x2a,
	0xc8, 0x6b, 0x50, 0x8c, 0x58, 0x90, 0x34, 0xeb, 0xaa, 0x4a, 0x9b, 0xb9, 0x55, 0xfa, 0x84, 0x05,
	0x9e, 0xf2, 0x22, 0x6f, 0x40, 0xa5, 0x47, 0x05, 0x0f, 0x3b, 0x49, 0xb3, 0xa1, 0x02, 0xd6, 0x72,
	0x03, 0x8e, 0x95, 0x8f, 0x67, 0x7c, 0x9d, 0x77, 0xa0, 0x6e, 0x50, 0x9e, 0x33, 0xe7, 0xbf, 0xb6,
	0xc0, 0x7e, 0xc2, 0x82, 0x34, 0xc5, 0xac, 0xd1, 0x14, 0x93, 0xe7, 0x31, 0xf7, 0x80, 0x1c, 0x93,
	0xfb, 0x60, 0x47, 0x2c, 0xd0, 0x77, 0xcf, 0xe6, 0xb8, 0x53, 0xc9, 0xbf, 0xf7, 0xfb, 0x82, 0x5f,
	0x79, 0xd2, 0xbb, 0xf5, 0x00, 0xaa, 0x46, 0x21, 0xb7, 0x70, 0x49, 0xaf, 0xcc, 0xe5, 0x7f, 0x49,
	0xaf, 0x24, 0xea, 0x5f, 0xf8, 0xd1, 0xc0, 0xac, 0x83, 0xc2, 0x5b, 0x85, 0x37, 0x2d, 0xe7, 0x9b,
	0x02, 0x94, 0xf1, 0xc8, 0x33, 0xef, 0xef, 0x01, 0xd8, 0xc2, 0x37, 0xfb, 0xdb, 0x9e, 0x00, 0xa2,
	0x7b, 0xe6, 0x9b, 0x2d, 0x0a, 0x3f, 0x20, 0x6f, 0x43, 0x19, 0x41, 0x6d, 0x16, 0x55, 0xe8, 0xbd,
	0x49, 0xa1, 0xf8, 0x0f, 0xa3, 0x75, 0x98, 0x3c, 0xa3, 0x99, 0xf1, 0xdf, 0x9c, 0xb1, 0xf5, 0x10,
	0xea, 0x99, 0xe9, 0xa6, 0x85, 0xda, 0x59, 0x78, 0x7e, 0xb0, 0xe0, 0xce, 0x21, 0x15, 0xe7, 0x09,
	0xe5, 0xa7, 0x58, 0x7b, 0xb7, 0xe6, 0xa7, 0xd3, 0xf9, 0xdb, 0x82, 0xe5, 0xd1, 0xbd, 0xcf, 0xf9,
	0x73, 0xf8, 0x21, 0xd4, 0xd4, 0x55, 0xd2, 0xee, 0xf9, 0xb1, 0xa6, 0xfd, 0xf5, 0x5c, 0xee, 0x6e,
	0xac, 0xe6, 0x1e, 0xc9, 0xb8, 0x63, 0x3f, 0x46, 0x22, 0xab, 0xa1, 0x16, 0x5b, 0x1f, 0xc3, 0xe2,
	0x88, 0x29, 0x87, 0x94, 0xbd, 0x2c, 0x29, 0xf2, 0x86, 0xcf, 0x5b, 0x51, 0x4d, 0x92, 0x25, 0xec,
	0x67, 0x0b, 0x56, 0x0e, 0xa9, 0x50, 0xfa, 0xdb, 0xc6, 0xd8, 0xf0, 0x02, 0x2f, 0x67, 0x2e, 0x70,
	0xe7, 0x2f, 0x0b, 0xc8, 0xb5, 0x23, 0xcd, 0x49, 0xe4, 0x07, 0x50, 0x95, 0x17, 0xfa, 0x2c, 0x3c,
	0x5e, 0x5b, 0xcd, 0x7d, 0xcc, 0x12, 0x91, 0xf2, 0x58, 0x79, 0x86, 0x52, 0xeb, 0x1c, 0x1a, 0x59,
	0x43, 0x0e, 0x8b, 0xbb, 0xa3, 0x2c, 0xe6, 0xb7, 0x52, 0x72, 0x8e, 0x2c, 0x89, 0xdf, 0x5b, 0xb0,
	0x64, 0xf6, 0x70, 0x9b, 0x2a, 0xee, 0x4f, 0x0b, 0x16, 0x87, 0xfb, 0x9e, 0x93, 0xa4, 0xe3, 0x9b,
	0xd5, 0xb6, 0x37, 0x91, 0xa5, 0xff, 0xa9, 0xd2, 0xbe, 0x82, 0x92, 0xd2, 0xe5, 0xfe, 0x6e, 0xac,
	0x40, 0xa9, 0xc3, 0x06, 0x7d, 0x6c, 0x39, 0x2c, 0x0f, 0x05, 0xd3, 0x28, 0xa9, 0xc6, 0x5a, 0xaa,
	0xb5, 0x34, 0xd2, 0x30, 0x14, 0x95, 0x65, 0xd8, 0x30, 0x0c, 0x5b, 0x83, 0x12, 0xc6, 0xa0, 0xe4,
	0xfc, 0x84, 0xef, 0x19, 0x95, 0x3a, 0xb7, 0xbe, 0xc4, 0x7f, 0xb3, 0xd4, 0xa3, 0x05, 0x0f, 0x33,
	0x67, 0xde, 0x1c, 0xdd, 0x28, 0x6e, 0x77, 0x5c, 0xda, 0xa4, 0xeb, 0xfc, 0xb7, 0x65, 0xfd, 0x8b,
	0x05, 0xc5, 0xc7, 0x6c, 0x6c, 0xa3, 0x6a, 0xda, 0xd1, 0xc2, 0x68, 0x3b, 0x9a, 0x61, 0x25, 0xcd,
	0x2d, 0x6c, 0x47, 0x31, 0x55, 0x74, 0x3b, 0x9a, 0x36, 0x96, 0xa5, 0xfc, 0xc6, 0xb2, 0x9c, 0xcd,
	0x9e, 0x6c, 0xf3, 0x5a, 0x19, 0xdf, 0xbc, 0x56, 0xaf, 0xe5, 0xe2, 0x48, 0x3b, 0x5a, 0x53, 0xc6,
	0xa1, 0xc2, 0xf9, 0xb6, 0xa0, 0xaa, 0x5f, 0x76, 0x9c, 0xb7, 0x3d, 0x21, 0xe5, 0xce, 0x23, 0x16,
	0x60, 0xa0, 0x06, 0x28, 0x62, 0x81, 0x0a, 0xd0, 0x26, 0xf5, 0x4a, 0xa8, 0xa6, 0x26, 0xc5, 0xeb,
	0x06, 0x34, 0xa4, 0x29, 0x3d, 0x33, 0x3e, 0x69, 0x20, 0x62, 0xc1, 0x19, 0x1e, 0xdb, 0xe9, 0x43,
	0xdd, 0x40, 0x34, 0x67, 0x9a, 0x9b, 0xa6, 0xdf, 0x9e, 0xa5, 0xe9, 0xdf, 0xff, 0xae, 0x0c, 0x70,
	0x8c, 0x1e, 0x07, 0x71, 0x48, 0x4e, 0xa0, 0x8c, 0x5f, 0x49, 0x88, 0x93, 0x1b, 0x38, 0xf2, 0x4d,
	0xa5, 0xb5, 0x31, 0xd1, 0x27, 0x8e, 0xae, 0x9c, 0x05, 0x72, 0x0a, 0x15, 0xfd, 0xb5, 0x81, 0x6c,
	0x8d, 0x2b, 0xb7, 0xcc, 0x37, 0x81, 0xd6, 0xe6, 0x64, 0x27, 0x9c, 0xf4, 0x13, 0x80, 0xe1, 0x5b,
	0x9b, 0xdc, 0xcd, 0x0d, 0xb9, 0xf1, 0xb9, 0xa1, 0xb5, 0x3d, 0xd5, 0x0f, 0x67, 0x3f, 0x81, 0x32,
	0xbe, 0x68, 0xc6, 0x80, 0x30, 0xf2, 0xa8, 0x1c, 0x03, 0x42, 0xe6, 0x49, 0xe4, 0x2c, 0x90, 0x0b,
	0x75, 0x7b, 0xa5, 0xad, 0x1f, 0xd9, 0x99, 0xa1, 0x3b, 0xc4, 0xd9, 0xef, 0xce, 0xd6, 0x47, 0x3a,
	0x0b, 0x84, 0x0e, 0x7f, 0x5a, 0x71, 0x91, 0x57, 0x66, 0x69, 0x5d, 0x70, 0x95, 0x7b, 0x33, 0x76,
	0x39, 0xce, 0x02, 0xf9, 0x08, 0xaa, 0x46, 0x4f, 0xb6, 0xa7, 0xfc, 0xec, 0xe2, 0xe4, 0xce, 0xf4,
	0x1f, 0xe7, 0x34, 0x4f, 0x54, 0x95, 0x6c, 0x4d, 0xbe, 0x96, 0xa7, 0xe4, 0x49, 0x7a, 0x77, 0x23,
	0x93, 0x58, 0x4d, 0x64, 0xec, 0x26, 0x86, 0xb7, 0xd1, 0x18, 0x26, 0x33, 0xe5, 0xe8, 0x2c, 0x3c,
	0xda, 0x83, 0xb5, 0x90, 0xb9, 0xd2, 0xe6, 0xd2, 0xe7, 0x7e, 0x2f, 0x8e, 0x68, 0xe2, 0x72, 0x36,
	0x10, 0x34, 0x18, 0x84, 0x5d, 0xfa, 0x68, 0xc9, 0x93, 0xe3, 0x43, 0x39, 0x3e, 0xe1, 0x4c, 0xb0,
	0x13, 0xeb, 0xa2, 0xac, 0xbe, 0xb8, 0xdc, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x77, 0x86,
	0x9e, 0xe3, 0x14, 0x00, 0x00,
}
