// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource_cluster_api_grpc_pb.proto

package resource_cluster_api_grpc_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_cluster_api_grpc_pb_1075a9fc3d98fa8b, []int{0}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_cluster_api_grpc_pb_1075a9fc3d98fa8b, []int{1}
}
func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (dst *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(dst, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetNodeRequest struct {
	Target               string   `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRequest) Reset()         { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()    {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_cluster_api_grpc_pb_1075a9fc3d98fa8b, []int{2}
}
func (m *GetNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRequest.Unmarshal(m, b)
}
func (m *GetNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRequest.Marshal(b, m, deterministic)
}
func (dst *GetNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRequest.Merge(dst, src)
}
func (m *GetNodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRequest.Size(m)
}
func (m *GetNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRequest proto.InternalMessageInfo

func (m *GetNodeRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type GetNodeReply struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeReply) Reset()         { *m = GetNodeReply{} }
func (m *GetNodeReply) String() string { return proto.CompactTextString(m) }
func (*GetNodeReply) ProtoMessage()    {}
func (*GetNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_cluster_api_grpc_pb_1075a9fc3d98fa8b, []int{3}
}
func (m *GetNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeReply.Unmarshal(m, b)
}
func (m *GetNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeReply.Marshal(b, m, deterministic)
}
func (dst *GetNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeReply.Merge(dst, src)
}
func (m *GetNodeReply) XXX_Size() int {
	return xxx_messageInfo_GetNodeReply.Size(m)
}
func (m *GetNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeReply proto.InternalMessageInfo

func (m *GetNodeReply) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type UpdateNodeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role" json:"role,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	StatusReason         string   `protobuf:"bytes,5,opt,name=status_reason,json=statusReason" json:"status_reason,omitempty"`
	State                string   `protobuf:"bytes,6,opt,name=state" json:"state,omitempty"`
	StateReason          string   `protobuf:"bytes,7,opt,name=state_reason,json=stateReason" json:"state_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeRequest) Reset()         { *m = UpdateNodeRequest{} }
func (m *UpdateNodeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeRequest) ProtoMessage()    {}
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_cluster_api_grpc_pb_1075a9fc3d98fa8b, []int{4}
}
func (m *UpdateNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeRequest.Unmarshal(m, b)
}
func (m *UpdateNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeRequest.Merge(dst, src)
}
func (m *UpdateNodeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeRequest.Size(m)
}
func (m *UpdateNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeRequest proto.InternalMessageInfo

func (m *UpdateNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateNodeRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *UpdateNodeRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UpdateNodeRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateNodeRequest) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *UpdateNodeRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *UpdateNodeRequest) GetStateReason() string {
	if m != nil {
		return m.StateReason
	}
	return ""
}

type UpdateNodeReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeReply) Reset()         { *m = UpdateNodeReply{} }
func (m *UpdateNodeReply) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeReply) ProtoMessage()    {}
func (*UpdateNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_cluster_api_grpc_pb_1075a9fc3d98fa8b, []int{5}
}
func (m *UpdateNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeReply.Unmarshal(m, b)
}
func (m *UpdateNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeReply.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeReply.Merge(dst, src)
}
func (m *UpdateNodeReply) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeReply.Size(m)
}
func (m *UpdateNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeReply proto.InternalMessageInfo

type Node struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Kind                 string               `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Role                 string               `protobuf:"bytes,3,opt,name=role" json:"role,omitempty"`
	Status               string               `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	StatusReason         string               `protobuf:"bytes,5,opt,name=status_reason,json=statusReason" json:"status_reason,omitempty"`
	State                string               `protobuf:"bytes,6,opt,name=state" json:"state,omitempty"`
	StateReason          string               `protobuf:"bytes,7,opt,name=state_reason,json=stateReason" json:"state_reason,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_cluster_api_grpc_pb_1075a9fc3d98fa8b, []int{6}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Node) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Node) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Node) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *Node) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Node) GetStateReason() string {
	if m != nil {
		return m.StateReason
	}
	return ""
}

func (m *Node) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Node) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "resource_cluster_api_grpc_pb.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "resource_cluster_api_grpc_pb.StatusReply")
	proto.RegisterType((*GetNodeRequest)(nil), "resource_cluster_api_grpc_pb.GetNodeRequest")
	proto.RegisterType((*GetNodeReply)(nil), "resource_cluster_api_grpc_pb.GetNodeReply")
	proto.RegisterType((*UpdateNodeRequest)(nil), "resource_cluster_api_grpc_pb.UpdateNodeRequest")
	proto.RegisterType((*UpdateNodeReply)(nil), "resource_cluster_api_grpc_pb.UpdateNodeReply")
	proto.RegisterType((*Node)(nil), "resource_cluster_api_grpc_pb.Node")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourceClusterApiClient is the client API for ResourceClusterApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceClusterApiClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeReply, error)
}

type resourceClusterApiClient struct {
	cc *grpc.ClientConn
}

func NewResourceClusterApiClient(cc *grpc.ClientConn) ResourceClusterApiClient {
	return &resourceClusterApiClient{cc}
}

func (c *resourceClusterApiClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/resource_cluster_api_grpc_pb.ResourceClusterApi/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClusterApiClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error) {
	out := new(GetNodeReply)
	err := c.cc.Invoke(ctx, "/resource_cluster_api_grpc_pb.ResourceClusterApi/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClusterApiClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeReply, error) {
	out := new(UpdateNodeReply)
	err := c.cc.Invoke(ctx, "/resource_cluster_api_grpc_pb.ResourceClusterApi/UpdateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceClusterApiServer is the server API for ResourceClusterApi service.
type ResourceClusterApiServer interface {
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeReply, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeReply, error)
}

func RegisterResourceClusterApiServer(s *grpc.Server, srv ResourceClusterApiServer) {
	s.RegisterService(&_ResourceClusterApi_serviceDesc, srv)
}

func _ResourceClusterApi_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceClusterApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource_cluster_api_grpc_pb.ResourceClusterApi/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceClusterApiServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceClusterApi_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceClusterApiServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource_cluster_api_grpc_pb.ResourceClusterApi/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceClusterApiServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceClusterApi_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceClusterApiServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource_cluster_api_grpc_pb.ResourceClusterApi/UpdateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceClusterApiServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceClusterApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resource_cluster_api_grpc_pb.ResourceClusterApi",
	HandlerType: (*ResourceClusterApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _ResourceClusterApi_Status_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _ResourceClusterApi_GetNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _ResourceClusterApi_UpdateNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource_cluster_api_grpc_pb.proto",
}

func init() {
	proto.RegisterFile("resource_cluster_api_grpc_pb.proto", fileDescriptor_resource_cluster_api_grpc_pb_1075a9fc3d98fa8b)
}

var fileDescriptor_resource_cluster_api_grpc_pb_1075a9fc3d98fa8b = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0x79, 0x95, 0xdc, 0xb4, 0x84, 0x8e, 0x10, 0xb2, 0x0c, 0x52, 0xc3, 0xb0, 0x09, 0x2f,
	0x07, 0x85, 0x0d, 0x2c, 0x53, 0x16, 0x65, 0x85, 0x2a, 0x03, 0x6b, 0x6b, 0x62, 0x5f, 0x2c, 0x0b,
	0xdb, 0x33, 0xcc, 0x43, 0xa2, 0x3f, 0xc5, 0x5f, 0xb0, 0xe6, 0x97, 0xd0, 0x3c, 0x0c, 0xad, 0x90,
	0x4c, 0xb6, 0xec, 0xce, 0x3d, 0xf7, 0x1c, 0xdf, 0xb9, 0x9e, 0x33, 0x40, 0x25, 0x2a, 0x6e, 0x64,
	0x81, 0x79, 0xd1, 0x18, 0xa5, 0x51, 0xe6, 0x4c, 0xd4, 0x79, 0x25, 0x45, 0x91, 0x8b, 0x7d, 0x2a,
	0x24, 0xd7, 0x9c, 0x3c, 0x1c, 0xd2, 0x24, 0x67, 0x15, 0xe7, 0x55, 0x83, 0x1b, 0xa7, 0xdd, 0x9b,
	0xcf, 0x1b, 0x5d, 0xb7, 0xa8, 0x34, 0x6b, 0x85, 0xb7, 0xd3, 0x25, 0x9c, 0x7c, 0xd0, 0x4c, 0x1b,
	0x95, 0xe1, 0x57, 0x83, 0x4a, 0xd3, 0x33, 0x58, 0xf4, 0x84, 0x68, 0xae, 0xc8, 0x5d, 0x18, 0xb7,
	0xaa, 0x8a, 0xa3, 0x55, 0xb4, 0x9e, 0x67, 0x16, 0xd2, 0x35, 0xdc, 0xb9, 0x40, 0xfd, 0x9e, 0x97,
	0x18, 0x2c, 0xe4, 0x3e, 0xcc, 0x34, 0x93, 0x15, 0xea, 0x20, 0x0b, 0x15, 0x7d, 0x07, 0xc7, 0xbf,
	0x95, 0xf6, 0x5b, 0xaf, 0x61, 0xda, 0xf1, 0x12, 0x55, 0x1c, 0xad, 0xc6, 0xeb, 0xc5, 0x96, 0xa6,
	0x83, 0xeb, 0x39, 0x9f, 0x37, 0xd0, 0x1f, 0x11, 0x9c, 0x7e, 0x12, 0x25, 0xd3, 0x78, 0x7d, 0x2e,
	0x81, 0x49, 0xc7, 0x5a, 0x0c, 0x53, 0x1d, 0xb6, 0xdc, 0x97, 0xba, 0x2b, 0xe3, 0x91, 0xe7, 0x2c,
	0xb6, 0x9c, 0xe4, 0x0d, 0xc6, 0x63, 0xcf, 0x59, 0x6c, 0xcf, 0xac, 0xdc, 0x9a, 0xf1, 0xc4, 0x9f,
	0xd9, 0x57, 0xe4, 0x31, 0x9c, 0x78, 0x94, 0x4b, 0x64, 0x8a, 0x77, 0xf1, 0xd4, 0xb5, 0x8f, 0x55,
	0xf8, 0x27, 0x96, 0x23, 0xf7, 0x60, 0x6a, 0x6b, 0x8c, 0x67, 0xae, 0xe9, 0x0b, 0xf2, 0x08, 0x9c,
	0x0a, 0x7b, 0xe7, 0x91, 0x6b, 0x2e, 0x1c, 0xe7, 0x8d, 0xf4, 0x14, 0x96, 0xd7, 0xd7, 0x10, 0xcd,
	0x15, 0xfd, 0x3e, 0x82, 0x89, 0xad, 0xfe, 0xbf, 0x6d, 0xc8, 0x1b, 0x00, 0xe3, 0xb6, 0x29, 0x73,
	0xa6, 0xe3, 0xdb, 0xab, 0x68, 0xbd, 0xd8, 0x26, 0xa9, 0x4f, 0x5c, 0xda, 0x27, 0x2e, 0xfd, 0xd8,
	0x27, 0x2e, 0x9b, 0x07, 0xf5, 0x4e, 0x5b, 0x6b, 0x21, 0xb1, 0xb7, 0xce, 0xff, 0x6d, 0x0d, 0xea,
	0x9d, 0xde, 0xfe, 0x1c, 0x01, 0xc9, 0x42, 0x70, 0xde, 0xfa, 0xdc, 0xec, 0x44, 0x4d, 0xf6, 0x30,
	0xf3, 0xb9, 0x25, 0xcf, 0x86, 0x73, 0x75, 0x23, 0xee, 0xc9, 0x93, 0xc3, 0xc4, 0xf6, 0xa6, 0x6e,
	0x11, 0x84, 0xa3, 0x10, 0x68, 0xf2, 0x7c, 0xd8, 0x77, 0xf3, 0x85, 0x24, 0x4f, 0x0f, 0x54, 0xfb,
	0x31, 0x1d, 0xc0, 0x9f, 0x94, 0x90, 0xcd, 0xb0, 0xf7, 0xaf, 0x67, 0x91, 0xbc, 0x38, 0xdc, 0xe0,
	0xe6, 0x9d, 0xbf, 0x84, 0x07, 0x35, 0x4f, 0x6d, 0x3f, 0xc5, 0x6f, 0xac, 0x15, 0x0d, 0xaa, 0x54,
	0x72, 0xa3, 0xb1, 0x32, 0x75, 0x89, 0xe7, 0xcb, 0xcc, 0xe2, 0x0b, 0x8b, 0x2f, 0xed, 0xcd, 0x5c,
	0x46, 0xfb, 0x99, 0xbb, 0xa2, 0x57, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x13, 0x34, 0xbd, 0x8c,
	0xa1, 0x04, 0x00, 0x00,
}
