// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor_agent_grpc_pb.proto

package monitor_agent_grpc_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_agent_grpc_pb_14623320d58105ce, []int{0}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_agent_grpc_pb_14623320d58105ce, []int{1}
}
func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (dst *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(dst, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *StatusReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "monitor_agent_grpc_pb.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "monitor_agent_grpc_pb.StatusReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorAgentClient is the client API for MonitorAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorAgentClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type monitorAgentClient struct {
	cc *grpc.ClientConn
}

func NewMonitorAgentClient(cc *grpc.ClientConn) MonitorAgentClient {
	return &monitorAgentClient{cc}
}

func (c *monitorAgentClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/monitor_agent_grpc_pb.MonitorAgent/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorAgentServer is the server API for MonitorAgent service.
type MonitorAgentServer interface {
	Status(context.Context, *StatusRequest) (*StatusReply, error)
}

func RegisterMonitorAgentServer(s *grpc.Server, srv MonitorAgentServer) {
	s.RegisterService(&_MonitorAgent_serviceDesc, srv)
}

func _MonitorAgent_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorAgentServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_agent_grpc_pb.MonitorAgent/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorAgentServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor_agent_grpc_pb.MonitorAgent",
	HandlerType: (*MonitorAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _MonitorAgent_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor_agent_grpc_pb.proto",
}

func init() {
	proto.RegisterFile("monitor_agent_grpc_pb.proto", fileDescriptor_monitor_agent_grpc_pb_14623320d58105ce)
}

var fileDescriptor_monitor_agent_grpc_pb_14623320d58105ce = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0xcd, 0xcf, 0xcb,
	0x2c, 0xc9, 0x2f, 0x8a, 0x4f, 0x4c, 0x4f, 0xcd, 0x2b, 0x89, 0x4f, 0x2f, 0x2a, 0x48, 0x8e, 0x2f,
	0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc5, 0x2a, 0xa9, 0xc4, 0xcf, 0xc5, 0x1b,
	0x5c, 0x92, 0x58, 0x52, 0x5a, 0x1c, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0xa2, 0x64, 0xc8, 0xc5,
	0x0d, 0x13, 0x28, 0xc8, 0xa9, 0x14, 0x12, 0xe0, 0x62, 0xce, 0x2d, 0x4e, 0x97, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x41, 0x22, 0xa9, 0x45, 0x45, 0x12, 0x4c, 0x10, 0x91, 0xd4, 0xa2,
	0x22, 0xa3, 0x14, 0x2e, 0x1e, 0x5f, 0x88, 0xe1, 0x8e, 0x20, 0xb3, 0x85, 0x42, 0xb8, 0xd8, 0x20,
	0x46, 0x08, 0xa9, 0xe8, 0x61, 0x77, 0x12, 0x8a, 0x95, 0x52, 0x4a, 0x04, 0x54, 0x15, 0xe4, 0x54,
	0x2a, 0x31, 0x38, 0x19, 0x70, 0x49, 0x67, 0xe6, 0xeb, 0x81, 0xe4, 0xf4, 0x52, 0x2b, 0x12, 0x73,
	0x0b, 0x72, 0x52, 0x8b, 0xf5, 0x8a, 0xf2, 0x4b, 0x4b, 0x52, 0xd3, 0x4b, 0x33, 0x53, 0x52, 0x9d,
	0xf8, 0x83, 0x40, 0x6c, 0x77, 0x10, 0x3b, 0x00, 0xe4, 0xe1, 0x00, 0xc6, 0x24, 0x36, 0xb0, 0xcf,
	0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x14, 0x1f, 0x0d, 0x18, 0x01, 0x00, 0x00,
}
