// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource_controller_grpc_pb.proto

package resource_controller_grpc_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f482d9d3d99de3ef, []int{0}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f482d9d3d99de3ef, []int{1}
}

func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (m *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(m, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *StatusReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "resource_controller_grpc_pb.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "resource_controller_grpc_pb.StatusReply")
}

func init() { proto.RegisterFile("resource_controller_grpc_pb.proto", fileDescriptor_f482d9d3d99de3ef) }

var fileDescriptor_f482d9d3d99de3ef = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x4a, 0x2d, 0xce,
	0x2f, 0x2d, 0x4a, 0x4e, 0x8d, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0xcf, 0xc9, 0x49, 0x2d, 0x8a,
	0x4f, 0x2f, 0x2a, 0x48, 0x8e, 0x2f, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xc6,
	0xa3, 0x44, 0x89, 0x9f, 0x8b, 0x37, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x38, 0x28, 0xb5, 0xb0, 0x34,
	0xb5, 0xb8, 0x44, 0xc9, 0x90, 0x8b, 0x1b, 0x26, 0x50, 0x90, 0x53, 0x29, 0x24, 0xc0, 0xc5, 0x9c,
	0x5b, 0x9c, 0x2e, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x82, 0x44, 0x52, 0x8b, 0x8a,
	0x24, 0x98, 0x20, 0x22, 0xa9, 0x45, 0x45, 0x46, 0x65, 0x5c, 0x42, 0x41, 0x50, 0x2b, 0x9c, 0xe1,
	0x36, 0x08, 0x25, 0x70, 0xb1, 0x41, 0x0c, 0x12, 0xd2, 0xd2, 0xc3, 0xe7, 0x48, 0x14, 0xeb, 0xa5,
	0x34, 0x88, 0x52, 0x5b, 0x90, 0x53, 0xa9, 0xc4, 0xe0, 0x64, 0xc0, 0x25, 0x9d, 0x99, 0xaf, 0x07,
	0x92, 0xd3, 0x4b, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x2d, 0xd6, 0x2b, 0xca, 0x2f, 0x2d, 0x49,
	0x4d, 0x2f, 0xcd, 0x4c, 0x49, 0x75, 0xe2, 0x0f, 0x02, 0xb1, 0xdd, 0x41, 0xec, 0x00, 0x50, 0x40,
	0x04, 0x30, 0x26, 0xb1, 0x81, 0x43, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xa4, 0xe9,
	0x2d, 0x36, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourceControllerClient is the client API for ResourceController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceControllerClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type resourceControllerClient struct {
	cc *grpc.ClientConn
}

func NewResourceControllerClient(cc *grpc.ClientConn) ResourceControllerClient {
	return &resourceControllerClient{cc}
}

func (c *resourceControllerClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/resource_controller_grpc_pb.ResourceController/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceControllerServer is the server API for ResourceController service.
type ResourceControllerServer interface {
	Status(context.Context, *StatusRequest) (*StatusReply, error)
}

func RegisterResourceControllerServer(s *grpc.Server, srv ResourceControllerServer) {
	s.RegisterService(&_ResourceController_serviceDesc, srv)
}

func _ResourceController_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceControllerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource_controller_grpc_pb.ResourceController/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceControllerServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resource_controller_grpc_pb.ResourceController",
	HandlerType: (*ResourceControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _ResourceController_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource_controller_grpc_pb.proto",
}
