// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource/resource_api/resource_api_grpc_pb/resource_api_grpc_pb.proto

package resource_api_grpc_pb // import "github.com/syunkitada/goapp/pkg/resource/resource_api/resource_api_grpc_pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import authproxy_grpc_pb "github.com/syunkitada/goapp/pkg/authproxy/authproxy_grpc_pb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{0}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{1}
}
func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (dst *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(dst, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//
// Action
//
type ActionRequest struct {
	Tctx                 *authproxy_grpc_pb.TraceContext `protobuf:"bytes,1,opt,name=Tctx" json:"Tctx,omitempty"`
	Queries              []*Query                        `protobuf:"bytes,2,rep,name=Queries" json:"Queries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ActionRequest) Reset()         { *m = ActionRequest{} }
func (m *ActionRequest) String() string { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()    {}
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{2}
}
func (m *ActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRequest.Unmarshal(m, b)
}
func (m *ActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRequest.Marshal(b, m, deterministic)
}
func (dst *ActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRequest.Merge(dst, src)
}
func (m *ActionRequest) XXX_Size() int {
	return xxx_messageInfo_ActionRequest.Size(m)
}
func (m *ActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRequest proto.InternalMessageInfo

func (m *ActionRequest) GetTctx() *authproxy_grpc_pb.TraceContext {
	if m != nil {
		return m.Tctx
	}
	return nil
}

func (m *ActionRequest) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

type Query struct {
	Kind                 string            `protobuf:"bytes,1,opt,name=Kind" json:"Kind,omitempty"`
	StrParams            map[string]string `protobuf:"bytes,2,rep,name=StrParams" json:"StrParams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NumParams            map[string]int64  `protobuf:"bytes,3,rep,name=NumParams" json:"NumParams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{3}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (dst *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(dst, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Query) GetStrParams() map[string]string {
	if m != nil {
		return m.StrParams
	}
	return nil
}

func (m *Query) GetNumParams() map[string]int64 {
	if m != nil {
		return m.NumParams
	}
	return nil
}

type ActionReply struct {
	Tctx                 *authproxy_grpc_pb.TraceContext `protobuf:"bytes,1,opt,name=Tctx" json:"Tctx,omitempty"`
	Index                string                          `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	Datacenters          []*Datacenter                   `protobuf:"bytes,3,rep,name=Datacenters" json:"Datacenters,omitempty"`
	Clusters             []*Cluster                      `protobuf:"bytes,4,rep,name=Clusters" json:"Clusters,omitempty"`
	Floors               []*Floor                        `protobuf:"bytes,5,rep,name=Floors" json:"Floors,omitempty"`
	Racks                []*Rack                         `protobuf:"bytes,6,rep,name=Racks" json:"Racks,omitempty"`
	PhysicalResources    []*PhysicalResource             `protobuf:"bytes,7,rep,name=PhysicalResources" json:"PhysicalResources,omitempty"`
	Nodes                []*Node                         `protobuf:"bytes,8,rep,name=Nodes" json:"Nodes,omitempty"`
	Computes             []*Compute                      `protobuf:"bytes,9,rep,name=Computes" json:"Computes,omitempty"`
	Networks             []*Network                      `protobuf:"bytes,10,rep,name=Networks" json:"Networks,omitempty"`
	Images               []*Image                        `protobuf:"bytes,11,rep,name=Images" json:"Images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ActionReply) Reset()         { *m = ActionReply{} }
func (m *ActionReply) String() string { return proto.CompactTextString(m) }
func (*ActionReply) ProtoMessage()    {}
func (*ActionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{4}
}
func (m *ActionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionReply.Unmarshal(m, b)
}
func (m *ActionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionReply.Marshal(b, m, deterministic)
}
func (dst *ActionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionReply.Merge(dst, src)
}
func (m *ActionReply) XXX_Size() int {
	return xxx_messageInfo_ActionReply.Size(m)
}
func (m *ActionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ActionReply proto.InternalMessageInfo

func (m *ActionReply) GetTctx() *authproxy_grpc_pb.TraceContext {
	if m != nil {
		return m.Tctx
	}
	return nil
}

func (m *ActionReply) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ActionReply) GetDatacenters() []*Datacenter {
	if m != nil {
		return m.Datacenters
	}
	return nil
}

func (m *ActionReply) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

func (m *ActionReply) GetFloors() []*Floor {
	if m != nil {
		return m.Floors
	}
	return nil
}

func (m *ActionReply) GetRacks() []*Rack {
	if m != nil {
		return m.Racks
	}
	return nil
}

func (m *ActionReply) GetPhysicalResources() []*PhysicalResource {
	if m != nil {
		return m.PhysicalResources
	}
	return nil
}

func (m *ActionReply) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ActionReply) GetComputes() []*Compute {
	if m != nil {
		return m.Computes
	}
	return nil
}

func (m *ActionReply) GetNetworks() []*Network {
	if m != nil {
		return m.Networks
	}
	return nil
}

func (m *ActionReply) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

//
// Node
//
type UpdateNodeRequest struct {
	Tctx                 *authproxy_grpc_pb.TraceContext `protobuf:"bytes,1,opt,name=Tctx" json:"Tctx,omitempty"`
	Node                 *Node                           `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateNodeRequest) Reset()         { *m = UpdateNodeRequest{} }
func (m *UpdateNodeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeRequest) ProtoMessage()    {}
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{5}
}
func (m *UpdateNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeRequest.Unmarshal(m, b)
}
func (m *UpdateNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeRequest.Merge(dst, src)
}
func (m *UpdateNodeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeRequest.Size(m)
}
func (m *UpdateNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeRequest proto.InternalMessageInfo

func (m *UpdateNodeRequest) GetTctx() *authproxy_grpc_pb.TraceContext {
	if m != nil {
		return m.Tctx
	}
	return nil
}

func (m *UpdateNodeRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type UpdateNodeReply struct {
	Tctx                 *authproxy_grpc_pb.TraceContext `protobuf:"bytes,1,opt,name=Tctx" json:"Tctx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateNodeReply) Reset()         { *m = UpdateNodeReply{} }
func (m *UpdateNodeReply) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeReply) ProtoMessage()    {}
func (*UpdateNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{6}
}
func (m *UpdateNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeReply.Unmarshal(m, b)
}
func (m *UpdateNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeReply.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeReply.Merge(dst, src)
}
func (m *UpdateNodeReply) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeReply.Size(m)
}
func (m *UpdateNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeReply proto.InternalMessageInfo

func (m *UpdateNodeReply) GetTctx() *authproxy_grpc_pb.TraceContext {
	if m != nil {
		return m.Tctx
	}
	return nil
}

//
// Resources
//
type Datacenter struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Kind                 string               `protobuf:"bytes,4,opt,name=Kind" json:"Kind,omitempty"`
	Region               string               `protobuf:"bytes,5,opt,name=Region" json:"Region,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Datacenter) Reset()         { *m = Datacenter{} }
func (m *Datacenter) String() string { return proto.CompactTextString(m) }
func (*Datacenter) ProtoMessage()    {}
func (*Datacenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{7}
}
func (m *Datacenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datacenter.Unmarshal(m, b)
}
func (m *Datacenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datacenter.Marshal(b, m, deterministic)
}
func (dst *Datacenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datacenter.Merge(dst, src)
}
func (m *Datacenter) XXX_Size() int {
	return xxx_messageInfo_Datacenter.Size(m)
}
func (m *Datacenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Datacenter.DiscardUnknown(m)
}

var xxx_messageInfo_Datacenter proto.InternalMessageInfo

func (m *Datacenter) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Datacenter) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Datacenter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Datacenter) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Datacenter) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type Floor struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Kind                 string               `protobuf:"bytes,4,opt,name=Kind" json:"Kind,omitempty"`
	Datacenter           string               `protobuf:"bytes,5,opt,name=Datacenter" json:"Datacenter,omitempty"`
	Zone                 string               `protobuf:"bytes,6,opt,name=Zone" json:"Zone,omitempty"`
	Floor                uint32               `protobuf:"varint,7,opt,name=Floor" json:"Floor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Floor) Reset()         { *m = Floor{} }
func (m *Floor) String() string { return proto.CompactTextString(m) }
func (*Floor) ProtoMessage()    {}
func (*Floor) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{8}
}
func (m *Floor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Floor.Unmarshal(m, b)
}
func (m *Floor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Floor.Marshal(b, m, deterministic)
}
func (dst *Floor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Floor.Merge(dst, src)
}
func (m *Floor) XXX_Size() int {
	return xxx_messageInfo_Floor.Size(m)
}
func (m *Floor) XXX_DiscardUnknown() {
	xxx_messageInfo_Floor.DiscardUnknown(m)
}

var xxx_messageInfo_Floor proto.InternalMessageInfo

func (m *Floor) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Floor) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Floor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Floor) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Floor) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *Floor) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Floor) GetFloor() uint32 {
	if m != nil {
		return m.Floor
	}
	return 0
}

type Rack struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Kind                 string               `protobuf:"bytes,4,opt,name=Kind" json:"Kind,omitempty"`
	Datacenter           string               `protobuf:"bytes,5,opt,name=Datacenter" json:"Datacenter,omitempty"`
	Floor                string               `protobuf:"bytes,6,opt,name=Floor" json:"Floor,omitempty"`
	Unit                 uint32               `protobuf:"varint,7,opt,name=Unit" json:"Unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Rack) Reset()         { *m = Rack{} }
func (m *Rack) String() string { return proto.CompactTextString(m) }
func (*Rack) ProtoMessage()    {}
func (*Rack) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{9}
}
func (m *Rack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rack.Unmarshal(m, b)
}
func (m *Rack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rack.Marshal(b, m, deterministic)
}
func (dst *Rack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rack.Merge(dst, src)
}
func (m *Rack) XXX_Size() int {
	return xxx_messageInfo_Rack.Size(m)
}
func (m *Rack) XXX_DiscardUnknown() {
	xxx_messageInfo_Rack.DiscardUnknown(m)
}

var xxx_messageInfo_Rack proto.InternalMessageInfo

func (m *Rack) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Rack) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Rack) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rack) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Rack) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *Rack) GetFloor() string {
	if m != nil {
		return m.Floor
	}
	return ""
}

func (m *Rack) GetUnit() uint32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

type PhysicalResource struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Kind                 string               `protobuf:"bytes,4,opt,name=Kind" json:"Kind,omitempty"`
	Datacenter           string               `protobuf:"bytes,5,opt,name=Datacenter" json:"Datacenter,omitempty"`
	Rack                 string               `protobuf:"bytes,6,opt,name=Rack" json:"Rack,omitempty"`
	Model                string               `protobuf:"bytes,7,opt,name=Model" json:"Model,omitempty"`
	RackPosition         string               `protobuf:"bytes,8,opt,name=RackPosition" json:"RackPosition,omitempty"`
	PowerLinks           []string             `protobuf:"bytes,9,rep,name=PowerLinks" json:"PowerLinks,omitempty"`
	NetLinks             []string             `protobuf:"bytes,10,rep,name=NetLinks" json:"NetLinks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PhysicalResource) Reset()         { *m = PhysicalResource{} }
func (m *PhysicalResource) String() string { return proto.CompactTextString(m) }
func (*PhysicalResource) ProtoMessage()    {}
func (*PhysicalResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{10}
}
func (m *PhysicalResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhysicalResource.Unmarshal(m, b)
}
func (m *PhysicalResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhysicalResource.Marshal(b, m, deterministic)
}
func (dst *PhysicalResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhysicalResource.Merge(dst, src)
}
func (m *PhysicalResource) XXX_Size() int {
	return xxx_messageInfo_PhysicalResource.Size(m)
}
func (m *PhysicalResource) XXX_DiscardUnknown() {
	xxx_messageInfo_PhysicalResource.DiscardUnknown(m)
}

var xxx_messageInfo_PhysicalResource proto.InternalMessageInfo

func (m *PhysicalResource) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *PhysicalResource) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PhysicalResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PhysicalResource) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *PhysicalResource) GetDatacenter() string {
	if m != nil {
		return m.Datacenter
	}
	return ""
}

func (m *PhysicalResource) GetRack() string {
	if m != nil {
		return m.Rack
	}
	return ""
}

func (m *PhysicalResource) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *PhysicalResource) GetRackPosition() string {
	if m != nil {
		return m.RackPosition
	}
	return ""
}

func (m *PhysicalResource) GetPowerLinks() []string {
	if m != nil {
		return m.PowerLinks
	}
	return nil
}

func (m *PhysicalResource) GetNetLinks() []string {
	if m != nil {
		return m.NetLinks
	}
	return nil
}

type Cluster struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{11}
}
func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (dst *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(dst, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Cluster) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Node struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	Id                   uint64               `protobuf:"varint,3,opt,name=Id" json:"Id,omitempty"`
	Cluster              string               `protobuf:"bytes,4,opt,name=Cluster" json:"Cluster,omitempty"`
	Kind                 string               `protobuf:"bytes,5,opt,name=Kind" json:"Kind,omitempty"`
	Name                 string               `protobuf:"bytes,6,opt,name=Name" json:"Name,omitempty"`
	Role                 string               `protobuf:"bytes,7,opt,name=Role" json:"Role,omitempty"`
	Status               string               `protobuf:"bytes,8,opt,name=Status" json:"Status,omitempty"`
	StatusReason         string               `protobuf:"bytes,9,opt,name=StatusReason" json:"StatusReason,omitempty"`
	State                string               `protobuf:"bytes,10,opt,name=State" json:"State,omitempty"`
	StateReason          string               `protobuf:"bytes,11,opt,name=StateReason" json:"StateReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{12}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Node) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Node) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Node) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Node) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Node) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *Node) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Node) GetStateReason() string {
	if m != nil {
		return m.StateReason
	}
	return ""
}

type Compute struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	Id                   uint64               `protobuf:"varint,3,opt,name=Id" json:"Id,omitempty"`
	Cluster              string               `protobuf:"bytes,4,opt,name=Cluster" json:"Cluster,omitempty"`
	Kind                 string               `protobuf:"bytes,5,opt,name=Kind" json:"Kind,omitempty"`
	Name                 string               `protobuf:"bytes,6,opt,name=Name" json:"Name,omitempty"`
	FullName             string               `protobuf:"bytes,7,opt,name=FullName" json:"FullName,omitempty"`
	Labels               string               `protobuf:"bytes,8,opt,name=Labels" json:"Labels,omitempty"`
	Status               string               `protobuf:"bytes,9,opt,name=Status" json:"Status,omitempty"`
	StatusReason         string               `protobuf:"bytes,10,opt,name=StatusReason" json:"StatusReason,omitempty"`
	Spec                 string               `protobuf:"bytes,11,opt,name=Spec" json:"Spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Compute) Reset()         { *m = Compute{} }
func (m *Compute) String() string { return proto.CompactTextString(m) }
func (*Compute) ProtoMessage()    {}
func (*Compute) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{13}
}
func (m *Compute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Compute.Unmarshal(m, b)
}
func (m *Compute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Compute.Marshal(b, m, deterministic)
}
func (dst *Compute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Compute.Merge(dst, src)
}
func (m *Compute) XXX_Size() int {
	return xxx_messageInfo_Compute.Size(m)
}
func (m *Compute) XXX_DiscardUnknown() {
	xxx_messageInfo_Compute.DiscardUnknown(m)
}

var xxx_messageInfo_Compute proto.InternalMessageInfo

func (m *Compute) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Compute) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Compute) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Compute) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Compute) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Compute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Compute) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Compute) GetLabels() string {
	if m != nil {
		return m.Labels
	}
	return ""
}

func (m *Compute) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Compute) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *Compute) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

type Network struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	Id                   uint64               `protobuf:"varint,3,opt,name=Id" json:"Id,omitempty"`
	Cluster              string               `protobuf:"bytes,4,opt,name=Cluster" json:"Cluster,omitempty"`
	Kind                 string               `protobuf:"bytes,5,opt,name=Kind" json:"Kind,omitempty"`
	Name                 string               `protobuf:"bytes,6,opt,name=Name" json:"Name,omitempty"`
	FullName             string               `protobuf:"bytes,7,opt,name=FullName" json:"FullName,omitempty"`
	Labels               string               `protobuf:"bytes,8,opt,name=Labels" json:"Labels,omitempty"`
	Status               string               `protobuf:"bytes,9,opt,name=Status" json:"Status,omitempty"`
	StatusReason         string               `protobuf:"bytes,10,opt,name=StatusReason" json:"StatusReason,omitempty"`
	Spec                 string               `protobuf:"bytes,11,opt,name=Spec" json:"Spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{14}
}
func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (dst *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(dst, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Network) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Network) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Network) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Network) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Network) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Network) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Network) GetLabels() string {
	if m != nil {
		return m.Labels
	}
	return ""
}

func (m *Network) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Network) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *Network) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

type Image struct {
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	Id                   uint64               `protobuf:"varint,3,opt,name=Id" json:"Id,omitempty"`
	Cluster              string               `protobuf:"bytes,4,opt,name=Cluster" json:"Cluster,omitempty"`
	Kind                 string               `protobuf:"bytes,5,opt,name=Kind" json:"Kind,omitempty"`
	Name                 string               `protobuf:"bytes,6,opt,name=Name" json:"Name,omitempty"`
	FullName             string               `protobuf:"bytes,7,opt,name=FullName" json:"FullName,omitempty"`
	Labels               string               `protobuf:"bytes,8,opt,name=Labels" json:"Labels,omitempty"`
	Status               string               `protobuf:"bytes,9,opt,name=Status" json:"Status,omitempty"`
	StatusReason         string               `protobuf:"bytes,10,opt,name=StatusReason" json:"StatusReason,omitempty"`
	Spec                 string               `protobuf:"bytes,11,opt,name=Spec" json:"Spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_api_grpc_pb_102907457abd7a5c, []int{15}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Image) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Image) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Image) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Image) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Image) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Image) GetLabels() string {
	if m != nil {
		return m.Labels
	}
	return ""
}

func (m *Image) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Image) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func (m *Image) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "resource_api_grpc_pb.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "resource_api_grpc_pb.StatusReply")
	proto.RegisterType((*ActionRequest)(nil), "resource_api_grpc_pb.ActionRequest")
	proto.RegisterType((*Query)(nil), "resource_api_grpc_pb.Query")
	proto.RegisterMapType((map[string]int64)(nil), "resource_api_grpc_pb.Query.NumParamsEntry")
	proto.RegisterMapType((map[string]string)(nil), "resource_api_grpc_pb.Query.StrParamsEntry")
	proto.RegisterType((*ActionReply)(nil), "resource_api_grpc_pb.ActionReply")
	proto.RegisterType((*UpdateNodeRequest)(nil), "resource_api_grpc_pb.UpdateNodeRequest")
	proto.RegisterType((*UpdateNodeReply)(nil), "resource_api_grpc_pb.UpdateNodeReply")
	proto.RegisterType((*Datacenter)(nil), "resource_api_grpc_pb.Datacenter")
	proto.RegisterType((*Floor)(nil), "resource_api_grpc_pb.Floor")
	proto.RegisterType((*Rack)(nil), "resource_api_grpc_pb.Rack")
	proto.RegisterType((*PhysicalResource)(nil), "resource_api_grpc_pb.PhysicalResource")
	proto.RegisterType((*Cluster)(nil), "resource_api_grpc_pb.Cluster")
	proto.RegisterType((*Node)(nil), "resource_api_grpc_pb.Node")
	proto.RegisterType((*Compute)(nil), "resource_api_grpc_pb.Compute")
	proto.RegisterType((*Network)(nil), "resource_api_grpc_pb.Network")
	proto.RegisterType((*Image)(nil), "resource_api_grpc_pb.Image")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourceApiClient is the client API for ResourceApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceApiClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionReply, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeReply, error)
}

type resourceApiClient struct {
	cc *grpc.ClientConn
}

func NewResourceApiClient(cc *grpc.ClientConn) ResourceApiClient {
	return &resourceApiClient{cc}
}

func (c *resourceApiClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/resource_api_grpc_pb.ResourceApi/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceApiClient) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionReply, error) {
	out := new(ActionReply)
	err := c.cc.Invoke(ctx, "/resource_api_grpc_pb.ResourceApi/Action", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceApiClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeReply, error) {
	out := new(UpdateNodeReply)
	err := c.cc.Invoke(ctx, "/resource_api_grpc_pb.ResourceApi/UpdateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceApiServer is the server API for ResourceApi service.
type ResourceApiServer interface {
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	Action(context.Context, *ActionRequest) (*ActionReply, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeReply, error)
}

func RegisterResourceApiServer(s *grpc.Server, srv ResourceApiServer) {
	s.RegisterService(&_ResourceApi_serviceDesc, srv)
}

func _ResourceApi_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource_api_grpc_pb.ResourceApi/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceApiServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceApi_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceApiServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource_api_grpc_pb.ResourceApi/Action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceApiServer).Action(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceApi_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceApiServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource_api_grpc_pb.ResourceApi/UpdateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceApiServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resource_api_grpc_pb.ResourceApi",
	HandlerType: (*ResourceApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _ResourceApi_Status_Handler,
		},
		{
			MethodName: "Action",
			Handler:    _ResourceApi_Action_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _ResourceApi_UpdateNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource/resource_api/resource_api_grpc_pb/resource_api_grpc_pb.proto",
}

func init() {
	proto.RegisterFile("resource/resource_api/resource_api_grpc_pb/resource_api_grpc_pb.proto", fileDescriptor_resource_api_grpc_pb_102907457abd7a5c)
}

var fileDescriptor_resource_api_grpc_pb_102907457abd7a5c = []byte{
	// 1054 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0xde, 0x38, 0x76, 0xd2, 0x9c, 0xfc, 0xba, 0xdd, 0x1d, 0x55, 0x3f, 0x59, 0x59, 0x41, 0x83,
	0x11, 0x50, 0x71, 0xe1, 0xa0, 0x56, 0x48, 0x0b, 0xe2, 0xa6, 0x2d, 0x5b, 0x28, 0xec, 0x56, 0x61,
	0xda, 0xbd, 0xd9, 0x0b, 0xaa, 0x89, 0x3d, 0xb8, 0x56, 0x1c, 0x8f, 0xf1, 0x8c, 0xd9, 0x44, 0xf0,
	0x12, 0x5c, 0xf0, 0x14, 0xbc, 0x04, 0xaf, 0x80, 0xe0, 0x82, 0x87, 0x80, 0x0b, 0xde, 0x00, 0xcd,
	0x1f, 0x3b, 0xce, 0xd6, 0x9b, 0xa2, 0x65, 0x25, 0x76, 0xd1, 0xde, 0x9d, 0x73, 0xe6, 0xfb, 0x8e,
	0x67, 0xbe, 0x73, 0x72, 0x3c, 0x0e, 0xdc, 0xcb, 0x29, 0x67, 0x45, 0x1e, 0xd0, 0x51, 0x69, 0x5c,
	0x90, 0x2c, 0x5e, 0x71, 0x2e, 0xa2, 0x3c, 0x0b, 0x2e, 0xb2, 0x49, 0x63, 0xd0, 0xcf, 0x72, 0x26,
	0x18, 0xda, 0x6e, 0x5a, 0x1b, 0xec, 0x44, 0x8c, 0x45, 0x09, 0x1d, 0x29, 0xcc, 0xa4, 0xf8, 0x6a,
	0x24, 0xe2, 0x19, 0xe5, 0x82, 0xcc, 0x32, 0x4d, 0x1b, 0xec, 0x93, 0x42, 0x5c, 0x66, 0x39, 0x9b,
	0x2f, 0x46, 0x95, 0x55, 0x3d, 0xee, 0x4a, 0x44, 0x93, 0xbc, 0x2d, 0xd8, 0x3c, 0x13, 0x44, 0x14,
	0x1c, 0xd3, 0xaf, 0x0b, 0xca, 0x85, 0xb7, 0x03, 0xfd, 0x32, 0x90, 0x25, 0x0b, 0x74, 0x0b, 0xda,
	0x0f, 0x78, 0xe4, 0xb6, 0x86, 0xad, 0xdd, 0x1e, 0x96, 0xa6, 0xf7, 0x2d, 0x6c, 0x1e, 0x04, 0x22,
	0x66, 0xa9, 0x61, 0xa0, 0x7d, 0xb0, 0xcf, 0x03, 0x31, 0x57, 0x98, 0xfe, 0xde, 0x8e, 0x7f, 0xf5,
	0x51, 0xe7, 0x39, 0x09, 0xe8, 0x11, 0x4b, 0x05, 0x9d, 0x0b, 0xac, 0xc0, 0xe8, 0x7d, 0xe8, 0x7e,
	0x51, 0xd0, 0x3c, 0xa6, 0xdc, 0xb5, 0x86, 0xed, 0xdd, 0xfe, 0xde, 0x1d, 0xbf, 0x51, 0x11, 0x09,
	0x5a, 0xe0, 0x12, 0xeb, 0xfd, 0x68, 0x81, 0xa3, 0x42, 0x08, 0x81, 0xfd, 0x79, 0x9c, 0x86, 0x66,
	0x67, 0xca, 0x46, 0x9f, 0x42, 0xef, 0x4c, 0xe4, 0x63, 0x92, 0x93, 0x59, 0x99, 0xf6, 0xdd, 0x35,
	0x69, 0xfd, 0x0a, 0x7c, 0x2f, 0x15, 0xf9, 0x02, 0x2f, 0xc9, 0x32, 0xd3, 0x69, 0x31, 0x33, 0x99,
	0xda, 0xd7, 0x67, 0xaa, 0xc0, 0x26, 0x53, 0xe5, 0x0f, 0x3e, 0x82, 0x9b, 0xab, 0x8f, 0x91, 0x92,
	0x4e, 0xe9, 0xa2, 0x94, 0x74, 0x4a, 0x17, 0x68, 0x1b, 0x9c, 0x6f, 0x48, 0x52, 0x50, 0xd7, 0x52,
	0x31, 0xed, 0x7c, 0x68, 0xdd, 0x6d, 0x49, 0xf6, 0x6a, 0xea, 0xeb, 0xd8, 0xed, 0x1a, 0xdb, 0xfb,
	0xd3, 0x86, 0x7e, 0x59, 0x2b, 0x59, 0xcc, 0x67, 0xaa, 0xd4, 0x36, 0x38, 0x71, 0x1a, 0xd2, 0x79,
	0xb9, 0x39, 0xe5, 0xa0, 0x43, 0xe8, 0x7f, 0x4c, 0x04, 0x09, 0x68, 0x2a, 0x68, 0x5e, 0x4a, 0x34,
	0x6c, 0x96, 0x68, 0x09, 0xc4, 0x75, 0x12, 0xfa, 0x00, 0x36, 0x8e, 0x92, 0x82, 0xab, 0x04, 0xb6,
	0x4a, 0xf0, 0x5a, 0x73, 0x02, 0x83, 0xc2, 0x15, 0x1c, 0xed, 0x43, 0xe7, 0x38, 0x61, 0x2c, 0xe7,
	0xae, 0xb3, 0xae, 0x7b, 0x14, 0x06, 0x1b, 0x28, 0x7a, 0x0f, 0x1c, 0x4c, 0x82, 0x29, 0x77, 0x3b,
	0x8a, 0x33, 0x68, 0xe6, 0x48, 0x08, 0xd6, 0x40, 0x74, 0x0e, 0xb7, 0xc7, 0x97, 0x0b, 0x1e, 0x07,
	0x24, 0xc1, 0x06, 0xcb, 0xdd, 0xae, 0x62, 0xbf, 0xdd, 0xcc, 0x7e, 0x12, 0x8e, 0xaf, 0x26, 0x90,
	0xfb, 0x38, 0x65, 0x21, 0xe5, 0xee, 0xc6, 0xba, 0x7d, 0x48, 0x08, 0xd6, 0x40, 0xa5, 0x14, 0x9b,
	0x65, 0x85, 0xa0, 0xdc, 0xed, 0xad, 0x55, 0x4a, 0xa3, 0x70, 0x05, 0x97, 0xd4, 0x53, 0x2a, 0x1e,
	0xb3, 0x7c, 0xca, 0x5d, 0x58, 0x47, 0x35, 0x28, 0x5c, 0xc1, 0xa5, 0xc8, 0x27, 0x33, 0x12, 0x51,
	0xee, 0xf6, 0xd7, 0x89, 0xac, 0x30, 0xd8, 0x40, 0xbd, 0x39, 0xdc, 0x7e, 0x98, 0x85, 0x44, 0x50,
	0xb5, 0xff, 0x7f, 0x32, 0x22, 0x7c, 0xb0, 0x53, 0x16, 0xea, 0xb6, 0x5e, 0xaf, 0x92, 0xc2, 0x79,
	0xc7, 0xb0, 0x55, 0x7f, 0xf2, 0xb3, 0x36, 0xbc, 0xf7, 0x53, 0x0b, 0x60, 0xd9, 0xa6, 0xe8, 0x2e,
	0xf4, 0x74, 0xda, 0xf0, 0x40, 0x98, 0x44, 0x03, 0x5f, 0xcf, 0x62, 0xbf, 0x9c, 0xc5, 0xfe, 0x79,
	0x39, 0x8b, 0xf1, 0x12, 0x2c, 0x99, 0x47, 0x39, 0x35, 0x4c, 0xeb, 0x7a, 0x66, 0x05, 0x96, 0xc3,
	0xed, 0x94, 0xcc, 0xa8, 0xdb, 0xd6, 0xc3, 0x4d, 0xda, 0xd5, 0xc0, 0xb3, 0x6b, 0x03, 0xef, 0xff,
	0xd0, 0xc1, 0x34, 0x8a, 0x59, 0xea, 0x3a, 0x2a, 0x6a, 0x3c, 0xef, 0x8f, 0x16, 0x38, 0xaa, 0xe9,
	0x5f, 0xe8, 0xdd, 0xbf, 0x5e, 0xd7, 0xd9, 0x9c, 0xa0, 0xae, 0x3c, 0x02, 0xfb, 0x11, 0x4b, 0xa9,
	0xdb, 0xd1, 0x1c, 0x69, 0xcb, 0x69, 0xa4, 0x0e, 0xe6, 0x76, 0x87, 0xad, 0xdd, 0x4d, 0xac, 0x1d,
	0xef, 0xf7, 0x16, 0xd8, 0xf2, 0x17, 0xfb, 0x52, 0x1f, 0xb7, 0x3a, 0x9a, 0x3e, 0xaf, 0x29, 0x20,
	0x02, 0xfb, 0x61, 0x1a, 0x0b, 0x73, 0x5e, 0x65, 0x7b, 0xbf, 0x59, 0x70, 0xeb, 0xc9, 0xb1, 0xf2,
	0xb2, 0x57, 0x5a, 0x96, 0xaf, 0xac, 0xb4, 0x2a, 0xe5, 0x36, 0x38, 0x0f, 0x58, 0x48, 0x13, 0x75,
	0xf2, 0x1e, 0xd6, 0x0e, 0xf2, 0xe0, 0x7f, 0x72, 0x75, 0xcc, 0x78, 0x2c, 0xdf, 0x6b, 0xee, 0x86,
	0x5a, 0x5c, 0x89, 0xc9, 0xa7, 0x8d, 0xd9, 0x63, 0x9a, 0xdf, 0x8f, 0xd3, 0xa9, 0x9e, 0x97, 0x3d,
	0x5c, 0x8b, 0xa0, 0x81, 0x1a, 0x89, 0x7a, 0x15, 0xd4, 0x6a, 0xe5, 0x7b, 0xdf, 0xb7, 0xa0, 0x6b,
	0xde, 0x32, 0x2f, 0x8a, 0xa2, 0xde, 0xaf, 0x16, 0xd8, 0x72, 0xa6, 0xfd, 0x2b, 0x1b, 0xba, 0x09,
	0xd6, 0x49, 0xa8, 0xb6, 0x63, 0x63, 0xeb, 0x24, 0x44, 0x6e, 0xa5, 0x8f, 0xa9, 0x70, 0x25, 0x57,
	0x59, 0x78, 0xa7, 0x56, 0xf8, 0xf2, 0x38, 0x9d, 0xd5, 0x06, 0xc1, 0x2c, 0xa1, 0xa6, 0xae, 0xca,
	0x96, 0x83, 0x4c, 0xdf, 0x3a, 0x4d, 0x41, 0x8d, 0x27, 0xcb, 0x5d, 0xde, 0x46, 0x09, 0x67, 0xa9,
	0xdb, 0xd3, 0xe5, 0xae, 0xc7, 0x64, 0xa3, 0x48, 0x9f, 0xba, 0xa0, 0x1b, 0x45, 0x39, 0x68, 0xa8,
	0xef, 0xb1, 0xd4, 0x10, 0xfb, 0x6a, 0xad, 0x1e, 0xf2, 0x7e, 0xb1, 0xa0, 0x6b, 0x5e, 0x93, 0xff,
	0x11, 0x65, 0x07, 0xb0, 0x71, 0x5c, 0x24, 0x89, 0x8a, 0x6b, 0x75, 0x2b, 0x5f, 0x2a, 0x7c, 0x9f,
	0x4c, 0x68, 0x52, 0x29, 0xac, 0xbd, 0x9a, 0xf2, 0xbd, 0xb5, 0xca, 0x43, 0x83, 0xf2, 0x08, 0xec,
	0xb3, 0x8c, 0x06, 0x46, 0x5c, 0x65, 0x2b, 0x55, 0xcd, 0x0d, 0xe2, 0x95, 0xaa, 0xcf, 0x4d, 0xd5,
	0x9f, 0x2d, 0x70, 0xd4, 0x05, 0xeb, 0x95, 0xa6, 0xcf, 0x4b, 0xd3, 0xbd, 0x1f, 0x2c, 0xe8, 0x97,
	0x6f, 0xcf, 0x83, 0x2c, 0x46, 0xb8, 0xcc, 0x8f, 0xde, 0x6c, 0xbe, 0x6b, 0xae, 0x7c, 0x28, 0x0f,
	0xde, 0x58, 0x0f, 0xca, 0x92, 0x85, 0x77, 0x43, 0xe6, 0xd4, 0x1f, 0x60, 0x4f, 0xcb, 0xb9, 0xf2,
	0x29, 0xfd, 0xb4, 0x9c, 0xb5, 0x6f, 0x38, 0xef, 0x06, 0xfa, 0x12, 0x60, 0x79, 0xcf, 0x45, 0xef,
	0x34, 0x53, 0xae, 0xdc, 0xc1, 0x07, 0x6f, 0x5d, 0x0f, 0x54, 0xf9, 0x0f, 0xbf, 0x83, 0x3b, 0x31,
	0xf3, 0xe5, 0xba, 0x4f, 0xe7, 0x64, 0x96, 0x25, 0x94, 0xfb, 0x39, 0x2b, 0x04, 0x8d, 0x8a, 0x38,
	0xa4, 0x87, 0x5b, 0x58, 0xda, 0x9f, 0x48, 0x7b, 0x2c, 0xbb, 0x66, 0xdc, 0x7a, 0xf4, 0x59, 0x14,
	0x8b, 0xcb, 0x62, 0xe2, 0x07, 0x6c, 0x36, 0xe2, 0x8b, 0x22, 0x9d, 0xc6, 0x82, 0x84, 0x64, 0x14,
	0x31, 0x92, 0x65, 0xa3, 0x6c, 0x1a, 0x8d, 0xfe, 0xfe, 0xff, 0x22, 0x93, 0x8e, 0x6a, 0xc5, 0xfd,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x27, 0x88, 0x7e, 0x4c, 0x11, 0x00, 0x00,
}
