// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor_alert_manager_grpc_pb.proto

package monitor_alert_manager_grpc_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_505ccd1ac96eed54, []int{0}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_505ccd1ac96eed54, []int{1}
}

func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (m *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(m, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *StatusReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "monitor_alert_manager_grpc_pb.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "monitor_alert_manager_grpc_pb.StatusReply")
}

func init() {
	proto.RegisterFile("monitor_alert_manager_grpc_pb.proto", fileDescriptor_505ccd1ac96eed54)
}

var fileDescriptor_505ccd1ac96eed54 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xce, 0xcd, 0xcf, 0xcb,
	0x2c, 0xc9, 0x2f, 0x8a, 0x4f, 0xcc, 0x49, 0x2d, 0x2a, 0x89, 0xcf, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f,
	0x2d, 0x8a, 0x4f, 0x2f, 0x2a, 0x48, 0x8e, 0x2f, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x92, 0xc5, 0xab, 0x48, 0x89, 0x9f, 0x8b, 0x37, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x38, 0x28, 0xb5,
	0xb0, 0x34, 0xb5, 0xb8, 0x44, 0xc9, 0x90, 0x8b, 0x1b, 0x26, 0x50, 0x90, 0x53, 0x29, 0x24, 0xc0,
	0xc5, 0x9c, 0x5b, 0x9c, 0x2e, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x82, 0x44, 0x52,
	0x8b, 0x8a, 0x24, 0x98, 0x20, 0x22, 0xa9, 0x45, 0x45, 0x46, 0xd5, 0x5c, 0xc2, 0xbe, 0x10, 0x4b,
	0x1c, 0x41, 0x76, 0xf8, 0x42, 0xac, 0x10, 0x4a, 0xe1, 0x62, 0x83, 0x98, 0x24, 0xa4, 0xa3, 0x87,
	0xdf, 0xa5, 0x28, 0x2e, 0x90, 0xd2, 0x22, 0x52, 0x75, 0x41, 0x4e, 0xa5, 0x12, 0x83, 0x93, 0x01,
	0x97, 0x74, 0x66, 0xbe, 0x1e, 0x48, 0x4e, 0x2f, 0xb5, 0x22, 0x31, 0xb7, 0x20, 0x27, 0xb5, 0x58,
	0xaf, 0x28, 0xbf, 0xb4, 0x24, 0x35, 0xbd, 0x34, 0x33, 0x25, 0xd5, 0x89, 0x3f, 0x08, 0xc4, 0x76,
	0x07, 0xb1, 0x03, 0x40, 0xe1, 0x11, 0xc0, 0x98, 0xc4, 0x06, 0x0e, 0x18, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x62, 0xec, 0xcf, 0xe7, 0x3f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorAlertManagerClient is the client API for MonitorAlertManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorAlertManagerClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type monitorAlertManagerClient struct {
	cc *grpc.ClientConn
}

func NewMonitorAlertManagerClient(cc *grpc.ClientConn) MonitorAlertManagerClient {
	return &monitorAlertManagerClient{cc}
}

func (c *monitorAlertManagerClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/monitor_alert_manager_grpc_pb.MonitorAlertManager/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorAlertManagerServer is the server API for MonitorAlertManager service.
type MonitorAlertManagerServer interface {
	Status(context.Context, *StatusRequest) (*StatusReply, error)
}

func RegisterMonitorAlertManagerServer(s *grpc.Server, srv MonitorAlertManagerServer) {
	s.RegisterService(&_MonitorAlertManager_serviceDesc, srv)
}

func _MonitorAlertManager_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorAlertManagerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor_alert_manager_grpc_pb.MonitorAlertManager/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorAlertManagerServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorAlertManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor_alert_manager_grpc_pb.MonitorAlertManager",
	HandlerType: (*MonitorAlertManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _MonitorAlertManager_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor_alert_manager_grpc_pb.proto",
}
